- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/Concept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/WriteService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
Sletter alle språkfelt for språkkoden som sendes inn.
Test:
* Kan kjøres lokalt
* Opprett ny språkversjon og slett igjen. Pass på at oppretta felt slettes igjen.
> Delete all language fields for concept.

- concept-api/src/main/scala/no/ndla/conceptapi/controller/DraftConceptController.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/api/DraftConceptSearchParams.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/search/DraftSearchSettings.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptSearchService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
Fixes NDLANO/Issues#2946
Slettede forklaringer skal ikke returneres i søk med mindre brukeren spesifiserer det.
> Add includeOtherStatuses param to concept-api search

- oembed-proxy/src/main/scala/ScalatraBootstrap.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/ComponentRegistry.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/JettyLauncher.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedProxyProperties.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedSwagger.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/CorrelationIdSupport.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/HealthController.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/OEmbedProxyController.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbed.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedEndpoint.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedProvider.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedServiceComponent.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/TestEnvironment.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/UnitSuite.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/controller/HealthControllerTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/controller/OEmbedProxyControllerTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedEndpointTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedProviderTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedServiceTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/ProviderServiceTest.scala
Fixes NDLANO/Issues#2989
Dersom remote provider returnerer 404 så videresendes dette til klienten. Ref 2.3.5. Errors i https://oembed.com/#section2
> Return 404 when remote returns 404

- article-api/src/main/scala/no/ndla/articleapi/service/search/ArticleSearchService.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/search/AudioSearchService.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/search/SeriesSearchService.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/search/TagSearchService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptSearchService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/AgreementSearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/ArticleSearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/GrepCodesSearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/TagSearchService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/ImageSearchService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/TagSearchService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
Setter `track_total_hits` parameteret ved søk slik at vi får tilbake nøyaktige antall resultater.
Kan testes ved å sjekke at `totalHits` i søkene gir riktige resultater (og ikke bare er cappet på 10.000)
> Set `track_total_hits` to true for all elasticsearch searches

- search-api/src/main/scala/no/ndla/searchapi/model/grep/GrepBundle.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/TaxonomyBundle.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
Bruker litt mer tid i starten på å bygge opp cacher (hashmaps) som er litt raskere å hente ut ifra enn å filtrere hver gang.
Etter profiling under indeksering så gikk vi fra ~92% til ~2% samples i `getTaxonomyContexts` (Det er veldig mye raskere)
Lokal kjøretid gikk fra litt over 6min til ~1.5min.
Når jeg testa litt i test så fikk jeg timeouts på indekserings requestene (Sikkert fordi de skjedde oftere).
Skrudde opp clusteret til å ha 5 noder (men indekserte før den ene kom opp) og 2cpuer og da gikk indekseringen i test på 4.5 minutter (!!!).
Tidligere har jeg opplevd at min lokale elasticsearch blir litt tregere etter hvert, men 4.5 minutter i k8s clusteret er fortsatt så mye raskere enn tidligere at jeg tror vi har fått speedet det opp betraktelig :smile:
Kan testes ved å sjekke at …
> Improve indexing performance in search-api

- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/Relevance.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/Resource.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/ResourceType.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/TaxonomyBundle.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
Fixes NDLANO/Issues#2930
Depends on https://github.com/NDLANO/taxonomy-api/pull/130
Kan testes ved å sjekke at brødsmulestier blir oversatt og at taxonomy-contexts som har en `visible: false` topic ikke vil bli indeksert for vanlige artikler (Fortsatt med for drafts).
> #2930: Support translations from taxonomy + hide non-visible contexts

- article-api/src/main/scala/no/ndla/articleapi/model/api/Availability.scala
- article-api/src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala
- article-api/src/main/scala/no/ndla/articleapi/model/api/TSTypes.scala
- article-api/src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- article-api/src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- article-api/typescript/index.ts
- draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/Availability.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/TSTypes.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- project/articleapi.scala
- project/draftapi.scala
Changed PartialPublish fields to use api instead of domain types, bnoth in article-api and draft-api. Generate new typescript types based on the changes.
> Partial publish domain to api

- validation/src/main/resources/embed-tag-rules.json
Relatert til https://github.com/NDLANO/Issues/issues/3016
Tekst er ikke relevant for blokkvisning av forklaring og burde derfor være optional
> Make text in concept embed optional

- concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableConcept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
Krever en reindeksering (men den kan kjøres før deploy med `ndla index build test --version <versjonmednyefelterher>`). 
Kan testes ved å sjekke at `created` og `articleIds` dukker opp i søkeresultater :^)
> Adds `articleIds` and `created` fields to concept-summary and indexes

- search-api/src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala
- search-api/src/main/scala/no/ndla/searchapi/model/api/RevisionMeta.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/Sort.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/draft/Draft.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/draft/RevisionMeta.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala
- search-api/src/test/scala/no/ndla/searchapi/integration/DraftApiClientTest.scala
- search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search/src/main/scala/no/ndla/search/model/SearchableLanguageFormats.scala
Legger til støtte for å søke i revisjonsnotaer, samt filtrere på og sortere på revisjonsdatoer for drafts i search-api.
Kan testes ved å lagre diverse revisjoner i drafts for så å prøve `sort=revisionDate`, `revision-date-from`og `revision-date-to` query-parameterene. Gjerne i kombinasjon.
> Adds search functionality for revisions

- draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleSummary.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/search/SearchableArticle.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/search/SearchableGrepCode.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/search/SearchableStatus.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/ArticleIndexService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
- draft-api/src/test/scala/no/ndla/draftapi/model/search/SearchableArticleSerializerTest.scala
Legger inn `status` så vi slipper å kalle /draft/${id} for hver eneste status vi vil hente ut i strukturredigeringen på ED.
> Add status field to ArticleSummary when searching for drafts

- article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- article-api/src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
Fixes NDLANO/Issues#3054
Viser seg at vi skipper over artikler med tomt document når vi dumper de i article-api. Dette gjør at avpubliserte artikler blir indeksert og dukker opp i det vanlige søket.
Kan testes ved å sjekke at en avpublisert artikkel ikke dukker opp i `/intern/dump/article` i article-api, evt at den ikke dukker opp i søket i search-api :smile:
> #3054: Ignore unpublished articles when dumping :^)

- article-api/src/main/scala/no/ndla/articleapi/integration/SearchApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/SearchApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
Sort of fixes NDLANO/Issues#3081
Inkrementell indeksering feiler fordi dei forskjellige apiene ikkje klarer å serialisere korrekt i kommunikasjonen mellom dei. Legger derfor på ekstra serialiseringsinfo i formats.
Må testes lokalt ved å ha ganske fullt oppsett i lokal docker.
* Sjekk ut pr og kjør `ndla deploy local draft-api` og tilsvarende for article-api og search-api.
* Kjør også ed lokalt slik at du kan åpne den på http://localhost:30019
* Finn en artikkel som er publisert, og gjør en endring i feks nøkkelord
* Artikkelen skal lagres i draft-api, draft-api sender indeksering til search-api og det skal gå bra. (ingen feilmelding i search-api)
* Fordi du har endra nøkkelord i en publisert artikkel vil draft-api gjøre en delpublisering til article-api og det skal gå bra. (ingen …
> Add extra formats for correct serializing

- image-api/src/main/scala/db/migration/V12__AddSizeMetaData.scala
- image-api/src/main/scala/no/ndla/imageapi/model/api/ImageDimensions.scala
- image-api/src/main/scala/no/ndla/imageapi/model/api/ImageMetaInformationV2.scala
- image-api/src/main/scala/no/ndla/imageapi/model/api/ImageMetaSummary.scala
- image-api/src/main/scala/no/ndla/imageapi/model/domain/ImageApiModels.scala
- image-api/src/main/scala/no/ndla/imageapi/model/search/SearchableImage.scala
- image-api/src/main/scala/no/ndla/imageapi/service/ConverterService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/ImageIndexService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
- image-api/src/test/scala/db/migration/V12__AddSizeMetaDataTest.scala
- image-api/src/test/scala/no/ndla/imageapi/TestData.scala
- image-api/src/test/scala/no/ndla/imageapi/controller/ImageControllerV2Test.scala
- image-api/src/test/scala/no/ndla/imageapi/controller/InternControllerTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/ConverterServiceTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/ReadServiceTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/ValidationServiceTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/WriteServiceTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/search/ImageSearchServiceTest.scala
- project/Module.scala
Relates to NDLANO/Issues#2846
Legger til `ImageDimensions` i databasen, samt eksponerer `imageDimensions`, `fileSize` og `contentType` i søkeresultater.
> #2846: Adds more image-api fields

- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/search/SearchIndexService.scala
This ensures nested learningsteps also are deleted so that deleted steps no longer prevents unpublishing of articles.
Om du sletter et steg, så oppdateres ikkje nested læringssteg slik at avpublisering av artikkelen fra steget blokkeres. Full reindeksering fikser problemet, men dette gjør at også inkrementell indeksering fungerer.
Test kjøres lokalt:
* Finn en læringssti og ta et vilkårlig steg. Finn artikkelen i ed og sjå at den er i bruk i stien.
* Rediger stien og slett steget.
* Sjekk i ed at stien ikkje lenger vises i lista over stier der artikkelen finnes.
> Delete learningpath from index before reindexing

- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- common/src/main/scala/no/ndla/common/ContentURIUtil.scala
- draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/SearchParams.scala
Fixes NDLANO/Issues#3087
Legger til endepunkt som tar inn en node-id og henter ut revisionMeta for tilhørende artikkel. Oppdaterer rekursivt alle underliggende artikler.
> 3087 add endpoint to update revisions

- .github/workflows/common_ci.yml
- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- article-api/src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- build.sbt
- common/src/main/scala/no/ndla/common/ContentURIUtil.scala
- common/src/test/scala/no/ndla/common/ContentURIUtilTest.scala
Oppdaget ikke vi fjernet en case her, og siden CI er litt på kjøret frem til vi får ryddet opp i pact så var det litt vanskelig å se i testene også. Denne fikser at `parseArticleIdAndRevision` kunne (og gjorde i article-api testene) kaste en exception istedet for å returnere `Failure`.
> Handle non-matching cases in `parseArticleIdAndRevision`

- article-api/src/main/scala/no/ndla/articleapi/DBMigrator.scala
Vi hadde en bug etter config-endringen hvor vi instansierte den samme migreringen to ganger istedetfor to forskjellige.
Ooog vi hadde glemt mange migreringer i article-api :^)
> Instantiate `R__SetArticleTypeFromTaxonomy` migration

- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/scala/no/ndla/validation/TagRules.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Relatert til NDLANO/Issues#3015
Legger til støtte for fag i concept-list embed for å kunne filtrere på det i tillegg til nøkkelord.
> Add support for subject filter in concept-list

- validation/src/main/resources/embed-tag-rules.json
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Misforsto litt hvordan optional-feltene fungerer. Det skal nå være valgfritt å sende inn subject-id på concept-list når tag og title er satt.
> Make subject id optional

- draft-api/src/main/scala/draftapi/db/migration/V37__AddIdToAllRevisionMeta.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/RevisionMeta.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/domain/Content.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/domain/RevisionMeta.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
NDLANO/Issues#3146
Legger til innslag i endringslogg ved behandling av revisjonsdatoer. Måtte legge til en id til revisionMeta for å kunne spore endringer.
> 3146 add versionlog when updating revisionmeta

- article-api/src/main/scala/no/ndla/articleapi/ArticleSwagger.scala
- article-api/src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- article-api/src/test/scala/no/ndla/articleapi/TestData.scala
- article-api/src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftSwagger.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/SearchApiClient.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
revisionDate i article-api settes til første uferdige revisjonsdato fra draft-api. Dersom den er None så betyr det at det ikkje finnes uferdige revisjondatoer, og dermed vil ikkje artikkelen validere.
> Sjekker at minst en revision er uferdig.

- image-api/src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/HealthController.scala
- image-api/src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala
Er litt usikker på hva de faktiske problemene vi opplevde var så gjør et forsøk på å ikke bruke `lazy` på database tingene.
Aner ikke hvorfor det skulle hatt noe å si, men jeg klarer ikke se så mye annet som kan være relevant ved første øyekast.
Fjerner også fetchingen av bilder i helsesjekken (Syns ikke det gir så mye verdi, og gjør at vi tar ut image-api podder selvom det er andre ting som er det faktiske problemet, feks databasen).
> Try to solve image-api problems

- search-api/src/main/scala/no/ndla/searchapi/controller/HealthController.scala
- search-api/src/test/scala/no/ndla/searchapi/controller/HealthControllerTest.scala
Det gir egentlig ikke meningen å drepe search-api pods dersom elasticsearch clusteret ikke er grønt, så fjerner denne delen av helsesjekken.
> Remove elasticsearch cluster status check

- image-api/src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala
- learningpath-api/src/main/resources/learningpathapi/db/migration/V16__CreateFolderTable.sql
- scalatestsuite/src/main/scala/no/ndla/scalatestsuite/IntegrationSuite.scala
Depends on https://github.com/NDLANO/deploy/pull/410
Denne tar i bruk `gen_random_uuid()` fra postgres 13 istedetfor å bruke `uuid-ossp`.
Da slipper vi å gi superuser-tilganger til learningpath_api brukeren i miljøene (og vi burde jo oppgradere etterhvert uansett så why not now)
> Use `gen_random_uuid()` from postgres rather than `uuid-ossp` and bump to postgres 13.6

- learningpath-api/src/main/resources/learningpathapi/db/migration/V17__FolderIndexes.sql
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Ganske drastiske ytelsesforbedringer ved store-trestrukturer (på kostnad av litt mindre lesbar kode).
Gikk fra sånn ~2.6s sekunder til ~100-150ms på uthenting av en stor struktur.
> Recursive SQL for folders and resources

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Breadcrumb.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Folder.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
- learningpath-api/typescript/index.ts
- learningpath-api/typescript/package.json
- scalatestsuite/src/main/scala/no/ndla/scalatestsuite/UnitTestSuite.scala
Første PR på div endringer for å gjøre det enklere å bruke fra frontend (Lager flere for at denne ikke skal bli alt for stor).
Hoved-endringen er at ressurser og subfolders er nå to felter istedet for et.
Gjør også noen andre "småting":
- Fikser så sortering på output fra rekursiv sql ikke har noe å si
- Remote så var ikke alltid rekkefølgen på radene som forventet så ble litt krøll, nå depender vi ikke på det.
- `parentId` felt på folder
- `resourceId` for metadata id på ressurser
- Breadcrumb er nå objekt istedetfor kun streng
- Forslag (med hjelp fra @N4G1) på hvordan vi kan være mer eksplisitt på at en test feiler om en `Try` er fail
> Split resources/subfolders into multiple fields

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/NdlaController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
Fikser så vi returnerer ressursen på `POST` av ressurser, og rydder opp i litt swagger-doc consistencies.
> Return `Resource` on `POST`

- learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Begrenser antall nesta foldre. Limit er tentativt satt til `5`. Vi tar utgangspunktet i at parent er rota og da er depth 0, og så kan det være max 5 nesta barn. Så praktisk sett kan det være 6 nesta foldre.
Kom med forslag hvis det er noe :)
> add nesting limitation to folders and subfolders

- validation/src/main/resources/embed-tag-rules.json
NDLANO/Issues#3044 (og NDLANO/Issues#3092)
Legger til alt-tekst for audio og brightcove. Sletter gamle embed-urler.
> Adding data-alt to audio and brightcove

- image-api/src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
- image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala
- image-api/src/test/scala/no/ndla/imageapi/service/WriteServiceTest.scala
Fixes NDLANO/Issues#3199
Vi slettet ikke fra imagefiledata tabellen med mindre imagemetadata også ble slettet. :smile:
Kan testes ved å se at sletting av språkvariant fjerner metadata (og "supportedLanguages" for språket man sletter)
> #3199: Handle deleting of file meta when deleting language

- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Kan testes ved å sjekke at vi returnerer 400 om man forsøker å opprette en mappe med samme navn som en av mappene som allerede finnes i mappen man oppretter i :^)
> Disallow duplicate folder names in folder

- article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ReadService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
Lager ny endepunkt i draft-api for å avlaste elastic-search. Dette endepunktet brukes til å hente artikler basert på id'er.
> New ids endpoint draft api

- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/controller/NdlaController.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala
Fikser problemet med at emner ikkje oppdateres etter endring av contenturi. Problemet var rett og slett at uten taxonomyhash header så hentes data fra publisert versjon, og der er det jo ikkje endra noko.
Har deploya release fra denne branchen i test for å verifisere at det virker, og då fikk eg oppdatert emnet i ed-pr. Men du må laste struktur på nytt for at nytt navn på emnet skal oppdateres. Kanskje oppdatere meldinga til bruker om at "Artikkel er bytta ut. Last sida på nytt for å vise endring."
> Force to update taxonomy draft

- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/FolderAndDirectChildren.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Rydder også litt opp i at automatisk rank ikke slår sammen ressurser og mapper 😄 
Kan testes ved å se at nye mapper på rotnivå får rank tilsvarende siste på rot + 1
> Fix automatic rank for root folder

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
Relates to NDLANO/Issues#3302
Kan testes ved å se at søk på draft-søket (`/editorial/`) inkluderer treff fra revisjons-loggen til vanlig, men ikke med `?exclude-revision-log=true`
> #3302: Add `exclude-revision-log` flag to multi draft search

- draft-api/src/main/scala/no/ndla/draftapi/integration/SearchApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/IndexService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Dette gjør at lagring ikke feiler dersom indekseringen feiler, men alt annet går igjennom.
Lar oss også gjøre lagringen asynkront slik at vi slipper å vente på indekseringen etter lagring.
> Do indexing asynchronous & don't fail request if failure

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/ConfigController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/config/ConfigMetaRestricted.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
Legger til GET endepunkt  i ConfigController på `/:config_key` for å kunne se write-lock status i databasen under eksamen.
> learningpath-api: Add GET endpoint to fetch config data

- learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V24__RenameFeideUserTable.sql
- learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/UserController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/MyNDLAUser.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/MyNDLAUser.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestEnvironment.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
- learningpath-api/typescript/index.ts
- project/learningpathapi.scala
Bytter navn fra `FeideUser` til `MyNDLAUser` for å unngå confusion. Vi bruker `feideUser` i feide sammenheng og den ble også brukt som navn på brukerprofil på min NDLA.
> change variable name from FeideUser to MyNDLAUser, to be more precise

- learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V25__RenameLearningpathWriteRestriction.sql
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/config/ConfigKey.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/config/ConfigMeta.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/ConfigControllerTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/ConfigRepositoryTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Fixes NDLANO/Issues#3346
Kan testes ved å se at å sette `MY_NDLA_WRITE_RESTRICTED` til "true" ikke lar en skrive til min-ndla, men vanlige læringsstier fortsatt fungerer, og motsatt for `IS_WRITE_RESTRICTED` flagget som allerede eksisterer.
> Add `MY_NDLA_WRITE_RESTRICTED` config-key

- common/src/main/scala/no/ndla/common/RequestLogger.scala
- common/src/main/scala/no/ndla/common/scalatra/NdlaControllerBase.scala
- common/src/main/scala/no/ndla/common/scalatra/NdlaRequestLogger.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/NdlaMiddleware.scala
- project/Module.scala
Flytter bygging av logge-strengene til en egen funksjon sånn at vi blir litt mer oppfordret til å ha samme format på loggingen i alle apiene (uavhengig av biblioteker)
Legger også til latency i frontpage-api :^)
> Improve logging in frontpage-api

- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
This makes search-page display primary as main search-result
> Sort contexts with primary first.

- learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/ScalatraBootstrap.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/StatsController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Stats.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestEnvironment.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/StatsControllerTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
Fixes NDLANO/Issues#3341
Adds stats-endpoint
Kan testes med lokal database:
* `ndla migrate db test local -c learningpath-api`
* `ndla  deploy local learningpath-api`
* `curl http://localhost/learningpath-api/v1/stats` 
Bør få resultat `{"numberOfUsers":49,"numberOfFolders":196,"numberOfResources":163,"numberOfTags":63}`
> Add stats-endpoint for fetching data about my ndla

- search-api/src/main/scala/no/ndla/searchapi/model/api/TopicPath.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/TaxonomyBundle.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
Siden vi ikke egentlig skal støtte flere parent-topics for en topic så feilet vi for dette tidligere. Det viser seg at på en eller annen magisk måte så skjer det innomellom alikevel. Klarer ikke finne ut hvorfor helt ennå, så godtar det, men logger feilen for å kanskje finne ut noe mer senere.
Flytter også på litt kode for å prøve å gjøre ting slightly mer lesbart.
> Stop failing on multiple parent topics when building context

- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
- draft-api/src/test/scala/no/ndla/draftapi/integration/TaxonomyApiClientTest.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
Fixes NDLANO/Issues#3385
Depends on https://github.com/NDLANO/deploy/pull/452
Jeg syns vi burde unngå 1minutter lange requests uansett, men dette kan være en plasterlapp enn så lenge :smile:
> #3385: Make taxonomy-api clients use internal url rather than api-gateway

- article-api/README.md
- article-api/src/main/scala/no/ndla/articleapi/db/migration/V40__ContentLinkEmbedChildren.scala
- article-api/src/test/scala/no/ndla/articleapi/db/migration/V40__ContentLinkEmbedChildrenTest.scala
- common/src/main/scala/no/ndla/common/errors/ValidationMessage.scala
- draft-api/src/main/scala/no/ndla/draftapi/db/migration/V41__ContentLinkEmbedChildren.scala
- draft-api/src/test/scala/no/ndla/draftapi/db/migration/V41__ContentLinkEmbedChildrenTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/scala/no/ndla/validation/HtmlTagRules.scala
- validation/src/main/scala/no/ndla/validation/TagRules.scala
- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/main/scala/no/ndla/validation/TextValidator.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Gjør om lenke-tekst til `ndlaembed`-barn istedetfor å ha en attributt.
Dette gjør at vi kan ha (forhåpentligvis enkel) html som tekst for en link.
> Move link-text to `ndlaembed` children

- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- article-api/src/main/scala/no/ndla/articleapi/controller/NdlaController.scala
- article-api/src/main/scala/no/ndla/articleapi/db/migrationwithdependencies/R__SetArticleLanguageFromTaxonomy.scala
- article-api/src/main/scala/no/ndla/articleapi/model/api/NDLAErrors.scala
- article-api/src/main/scala/no/ndla/articleapi/model/domain/ArticleRow.scala
- article-api/src/main/scala/no/ndla/articleapi/model/domain/DBArticle.scala
- article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
- article-api/src/main/scala/no/ndla/articleapi/service/WriteService.scala
- article-api/src/test/scala/no/ndla/articleapi/UnitSuite.scala
- article-api/src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
- article-api/src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- article-api/src/test/scala/no/ndla/articleapi/service/WriteServiceTest.scala
Relates to https://github.com/NDLANO/Issues/issues/3386
Lager en wrapper klasse for å ha kontroll på forskjellen på document=`NULL` og en manglende rad.
> article-api: Return 410 GONE when article has been unpublished

- article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
Prøvde å hente ut artikler i frontend, ser at `data-url` mangler når artikkelen blir fetcha. 
Har ikke backend satt opp/aner ikke hvordan man kan teste med lokal swagger men ser at det blir mappa over artikkelen for å legge til URLer når man henter på ID.
> Map urls to embeds

- article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- audio-api/src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- common/src/main/scala/no/ndla/common/secrets/Secrets.scala
- concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/FrontpageApiProperties.scala
- image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
Ingen endringer, kun gjør det mulig å overstyre antall koblinger mot database. Defaulter til gammel verdi.
> Make max connections customizable

- frontpage-api/src/main/scala/no/ndla/frontpageapi/ComponentRegistry.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/Routes.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/Error.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/FilmPageControllerTest.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/SubjectPageControllerTest.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/TestEnvironment.scala
La merke til at vi tidligere bare fallbacka til `GENERIC` responsbody for 400 requests så la til en `BAD REQUEST` greie som ligner litt mer på det vi gjør i andre apier.
> Add custom `BAD REQUEST` json response body for request decoding

- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/articleapi/ArticleApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/draftapi/DraftApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/learningpathapi/LearningpathApiClientTest.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
Fjerner bruk av futures ved indeksering av search-api.
Problemet var at håndtering av futures ikkje fungerte i gammel løsning, men det var det som gjorde at det faktisk virka.
Så tester å fjerne dette slik at indeksering skjer synkront.
Deployer dette til test.
> Index search-api synchronized

- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
Sjekker at innsendt verdi er forskjellig fra eksisterende før ny timestamp settes.
> Only set responsible if responsibleId actually changes

- network/src/main/scala/no/ndla/network/clients/FeideApiClient.scala
There might be cases where Feide user has both student and employee affiliation. In those cases we want to assign the lowest privileged role which is the Student role.
> Fix role assignment algorithm

- concept-api/src/main/scala/no/ndla/conceptapi/model/api/UpdatedConcept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
Meg bekjent så er ikke dette tatt i bruk ennå, og det er enklere for alle om feltet heter det samme i `UpdatedConcept` og `NewConcept` :smile:
> Be consistent with `reponsibleId` field in `UpdatedConcept` and `NewConcept`

- common/src/main/scala/no/ndla/common/implicits/package.scala
- common/src/test/scala/no/ndla/common/QuestionMarkOperatorTest.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FilmPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FrontPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/InternController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/Service.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/Error.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/repository/SubjectPageRepository.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ReadService.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/WriteService.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/service/ReadServiceTest.scala
Fixes NDLANO/Issues#3450
- Legger til endepunkt `/frontpage-api/v1/subjectpages/`
- Legger til tester for spørsmålstegn operatorene :smile: 
- Gjør feilhåndtering litt mer generisk
- Tidligere så endte vi med å ikke logge feil skikkelig siden vi bare returnerte 500 og ikke gjorde noe med feilen. Nå blir alle feil på en eller annen måte sendt igjennom `ErrorHelpers.returnError`
> #3450: Add "all subject pages" endpoint

- concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/ConverterServiceTest.scala
Samme endring som i draft-api, kun oppdater tidsstempel dersom ansvarlig faktisk endres.
> Only update responsible timestamp when id changes.

- validation/src/main/resources/html-rules.json
relates to https://github.com/NDLANO/Issues/issues/3419
Trenger støtte for de nye html TAGene som skal brukes.
> Validation: Added new html tags

- search-api/src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Endrer bruk av context-types parameter til kun returnere ting som ligger i kontekst.
Ønsket er at emne-gruppa i søket kun skal returnerere emner i taksonomi. Og i og med at parameteret er context-type så gir det meining at kun ting som har kontekst returneres.
> Context-types only returns contexts in taxonomy.

- learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala
- network/src/main/scala/no/ndla/network/TaxonomyData.scala
- search-api/src/main/scala/no/ndla/searchapi/caching/Memoize.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/InternController.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/GrepApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/service/StandaloneIndexing.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/caching/MemoizeTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
Kjørte `/intern/index/` på search-api og det ser ut til å fungere. Gjerne sjekk de andre path'ene og se om data har mening
> search-api: distinguish between draft and public taxonomy

- network/src/main/scala/no/ndla/network/scalatra/NdlaScalatraServer.scala
- project/Dependencies.scala
Skipper å sende metrics fra javamelody til cloudwatch. Det er masse data som vi aldri ser på.
> Bump javamelody. Do not send metrics to cloudwatch

- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/Concept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/StateTransition.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/StateTransitionRules.scala
- concept-api/src/main/scala/no/ndla/conceptapi/validation/ContentValidator.scala
- concept-api/src/test/scala/no/ndla/conceptapi/TestData.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/StateTransitionRulesTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/validation/ContentValidatorTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
Tror dette er nok for at vi skal kunne skrive om til en request for status-endring + lagring i editorial.
> draft-api: Allow manual status-change on PATCH endpoint

- draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
Fixes NDLANO/Issues#3493
Beholder ansvarlig ved oppretting av ny versjon fra ed.
> Don't reset responsible if save as new from editorial

- draft-api/src/main/scala/no/ndla/draftapi/integration/LearningpathApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
Slutter å bruke tilsvarende kode i draft-api som finnes i learningpath-api
> Endre endepunkt for å sjekke bruk av artikkel

- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Løser egentlig samme problem som denne https://github.com/NDLANO/backend/pull/201, bare bittelitt mer future-safe.
Før så fant vi bare første optional-group med en tag som matcha når vi skulle validere en attributt og så om alle var fylt ut.
Nå finner vi alle utfylte optional groups og sjekker om det er noen optional tags igjen.
> validation: Improve selection of optional tag groups

- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Fixes: https://github.com/NDLANO/Issues/issues/3522
Deler nye foldere automatisk dersom parent folder har status delt.
Skrev tester for å dobbeltsjekke funksjonalitet
> share new folders automatically if parent is shared

- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/Sort.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/Sort.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
Legger til sortering for søk i {draft,concept}-api :smile:
Kan testes ved å spinne opp draft og concept og teste at `status` og `-status` fungerer som sorterings-parametere.
> Sorting in search

- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
Oppdaget en bug der kommentarer returneres i omvendt rekkefølge når man sender inn flere om gangen, feks med følgende json:
```
{
"revision": 31,
"title": "vi prøver ny tittel3222111",
"language": "nb",
"responsibleId": "hd5ZL5Lm4kKkumWgN2gjy9wx",
"comments": [{"content": "2"}, {"content": "1"}]
}
```
så vil kommentarene returneres i omvendt rekkefølge fra draft-api.
Jeg tenker det gir mening at ingen sortering skjer i backend, og at rekkefølgen bestemmes av frontend, de vil jo da automatisk alltid være i riktig rekkefølge basert på når de opprettes..
> draft-api: Remove reverse sorting for comments

- validation/src/main/resources/embed-tag-rules.json
I Editorial nå så lagres/sendes `imageId` som `image-id` som data tag, det hadde ikke jeg tatt høyde for.
> Validation: image-id to match new attributemethod in frontend

- draft-api/src/main/scala/no/ndla/draftapi/model/api/UpdatedUserData.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/UserData.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/domain/Content.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/TestData.scala
Vi trenger `latestEditedConcepts` på brukerobjektet for å ha kontroll på hvilke som er de siste redigerte forklaringene til en bruker :^)
Føles litt weird i draft-api, men vi har ingen bruker-objekter på samme måte noe annet sted og dette inneholder allerede ikke-draft-ting så tenker det er beste plassen.
> draft-api: Add `latestEditedConcepts` to user data

- article-api/src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/scala/no/ndla/validation/TagRules.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Partly fixes https://github.com/NDLANO/Issues/issues/3515
Legger `isdecor` attributtet på bilde embeds.
Fikk testet at `isdecor` attributtet havner i article-api etter publisering.
> Decorative images

- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/SideEffect.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/StateTransitionRules.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/StateTransitionRulesTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/SideEffect.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
fixes https://trello.com/c/qmrJUVWW/59-automatisk-sette-seg-selv-som-ansvarlig-p%C3%A5-statusendring-publisert-i-arbeid
Setter seg selv som responsible automatisk på statusskifte fra PUBLISHED -> IN_PROGRESS. Oppdatert både i draft-api og i concept-api.
> draft-api, concept-api: Automatically set responsible on status change

- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/SearchServiceTest.scala
Brukte litt tid på å finne ut hvorfor aggregeringer med paths som ikke finnes ikke returnerte og fant ut at vi ikke hadde noen "exit-path" i rekursjonen i denne contexten.
La til en og refaktorerte koden så den ble kanskje litt mer lesbar :smile:
> search-api: Fix non-existing aggregation path running forever

- network/src/main/scala/no/ndla/network/tapir/TapirServer.scala
Defaulten her viste seg å være veldig lav (30s idle og 60s async).
Vet ikke om det er dumt å ikke ha timeouts, men det er det vi er vant til fra scalatra i alle fall :shrug:
> No timeout for tapir requests

- concept-api/src/main/scala/no/ndla/conceptapi/service/StateTransitionRules.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
Quickfix frem til conteksten kan bli håndtert med `IOLocal`
> Set request context manually in side-effect `IO`

- search-api/src/main/scala/no/ndla/searchapi/model/api/MultiSearchTermsAggregation.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/TermAggregation.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
- search/src/main/scala/no/ndla/search/Elastic4sClient.scala
Fixing the linting to not do implicit widening of Int->Long made the
cast in `handleBucketResult` fail.
This patch fixes that and also introduces a test that would catch this
in case of regressions :^)
> search-api: Fix search-aggregation regression

- audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- audio-api/src/main/scala/no/ndla/audioapi/model/api/Error.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/InternController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/ErrorHelpers.scala
- network/src/main/scala/no/ndla/network/tapir/TapirErrorHelpers.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
Etter jeg og @N4G1 brukte lengere tid enn jeg drømte om for å finne ut hvorfor en serialisering feilet i en test så har jeg litt lyst at disse stacktracene skal bli med i tester.
Løser det med å bruke `ex.printStackTrace()` istedet for å passe selve exceptionen til loggeren.
Gjør det samtidig generisk ved å flytte fallback-casen til `TapirErrorHelpers` og la api'ene override `handleError` istedet.
> Move generic error to `TapirErrorHelpers`

- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/resources/html-rules.json
- validation/src/main/scala/no/ndla/validation/TagRules.scala
- validation/src/test/scala/no/ndla/validation/HtmlTagRulesTest.scala
Rewrote test to check for valid data-attributes. Added parallax-attribute
Tror testen fungerer på tilnærmet lik måte. Sjekker heller nå at alle legalEmbedattributes finnes i haugen av data attributter
> Flipped validation test 

- project/searchapi.scala
- search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
Fant ut at i test så dukker path som starter med /programme opp i søket. Dette er fordi kontekster behandles likt uavhengig av rota, og siden programområde-kontekster endå er skjult så må disse filtreres ut.
Sjekk Testemne her https://test.ndla.no/search?query=test
> filter out context starting with subject

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
The scalatra-swagger cannot understand the `UUID` type. Lets use string
and specify `UUID` in the descriptions :^)
> learningpath-api: Fix swagger doc by not using `UUID` type

- common/src/main/scala/no/ndla/common/model/NDLADate.scala
- common/src/test/scala/no/ndla/common/model/NDLADateTest.scala
- common/src/test/scala/no/ndla/common/model/TestObjectWithDate.scala
- common/src/test/scala/no/ndla/common/model/TestObjectWithOptionalDate.scala
- image-api/src/test/scala/no/ndla/imageapi/service/ReadServiceTest.scala
- project/commonlib.scala
- typescript/article-api.ts
- typescript/audio-api.ts
- typescript/concept-api.ts
- typescript/draft-api.ts
- typescript/frontpage-api.ts
- typescript/image-api.ts
- typescript/learningpath-api.ts
- typescript/search-api.ts
- Overså visst at `NDLADate` ville bli en type i typescript så fikser det blir strenger som tidligere.
- Gjør også at json4s "feiler" på samme måte som før dersom dato parsingen feiler.
- Det gjør feilmeldingene litt bedre
- Det gjør også at en feilende `Option[NDLADate]` vil bli til `None`
- Liker ikke helt det, men det er sånn det var før, og feilmeldingene er sikkert verdt det. Syns vi burde prøve å unngå å bruke det though. Vil mest sannsynlig brekke når vi går over til en bedre parser (circe :smile:)
> `NDLADate` typescript types & json4s serialization fix

- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- article-api/src/test/scala/no/ndla/articleapi/controller/ArticleControllerV2Test.scala
Bug fra tapir omskrivningen. Rekkefølgen gjorde at `/ids` ble parset som en slug og det gir jo ikke helt mening :smile:
Kan testes ved å sjekke at `/ids/` endepunktet fungerer som det skal :^)
> article-api: Make `/ids` endpoint not being parsed as slug

- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/FrontPage.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/controller/FrontPageControllerTest.scala
Noe rart gjorde at denne encoderen ikke fungerte skikkelig.
Man fikk `JSON decoding to CNil should never happen at 'menu[0].menu[0]'` dersom man prøvde å poste en json struktur med nestet `menu`.
Kan testes ved å kjøre en request som ligner på denne og se at du får 200 og ikke 400
```http 
POST /frontpage-api/v1/frontpage
{
"articleId": 38247,
"menu": [
{
"articleId": 38253,
"menu": [
{
"articleId": 38002,
"menu": [
{
"articleId": 38253,
"menu": []
}
]
}
]
},
{
"articleId": 38247,
"menu": []
}
]
}
```
> frontpage-api: Fix encoding error with `api.FrontPage`

- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
Gjør at man kan klone folders inn i steder med navnekonflikter. Legger på `_Kopi` (åpen for forslag) postfix dersom det er en konflikt.
> learningpath-api: Enable folder cloning with conflicting name

- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Fikser så delpubliserte felter ikke trigger `started` feltet.
Ref: https://trello.com/c/gp7zWSp2/327-p%C3%A5begynt-ressurs#comment-64de1526291e04033efa6eb7
> draft-api: Make partial published fields trigger `started`

- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Stats.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/StatsControllerTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
Legger på stats separert for ressurstype. Kan sikkert gjøres bedre men det funker.
Data fra test gir meg 
```
{
"numberOfUsers": 4992,
"numberOfFolders": 9639,
"numberOfResources": 8727,
"numberOfTags": 803,
"numberOfSubjects": 110,
"numberOfSharedFolders": 113,
"favouritedResources": [
{
"type": "multidisciplinary",
"number": 29
},
{
"type": "learningpath",
"number": 448
},
{
"type": "video",
"number": 14
},
{
"type": "audio",
"number": 3
},
{
"type": "concept",
"number": 5
},
{
"type": "image",
"number": 37
},
{
"type": "article",
"number": 8191
}
]
}
```
> Extend stats with grouped values

- article-api/src/main/scala/no/ndla/articleapi/controller/InternController.scala
- article-api/src/main/scala/no/ndla/articleapi/integration/SearchApiClient.scala
- article-api/src/test/scala/no/ndla/articleapi/controller/InternControllerTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
- network/src/main/scala/no/ndla/network/NdlaClient.scala
- network/src/test/scala/no/ndla/network/NdlaClientTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedServiceTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/ProviderServiceTest.scala
Fixes NDLANO/Issues#3696
Var visst et par problemer her.
- ExternalIds ble sendt med som query-parameter selv om listen var tom. 
- Det ble tolket av endepunktet som `List("")` så vi endte opp med å bruke soft-valideringen selvom vi ikke skulle det
- Vi ignorerte feilen fra article-api requesten med et uhell.
Kan testes ved å sjekke at publisering fungerer når det skal og feiler når det skal.
Testcasen fra issuet var at den skulle feile når metadescription var tom.
> draft-api: Stop ignoring error in `ArticleApiClient`

- audio-api/src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
- audio-api/src/main/scala/no/ndla/audioapi/ComponentRegistry.scala
- common/src/main/scala/no/ndla/common/Environment.scala
- draft-api/src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- image-api/src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
- image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
- project/commonlib.scala
Fjerner auto-oppdagelse av aws region by default og introduserer miljøvariabler for å spesifisere.
Egentlig mest for å fjerne støyete logging dersom auto-oppdagelsen feiler (lokalt og på CI), men gir også mer mening sånn her, siden det ikke er noen automatikk i at applikasjonene må kjøre i samme region som s3-bøttene.
Så tenkte det var ryddig uansett.
Ny oppførsel:
- Default uten variabel så blir regionen nå `eu-west-1`
- Spesifisert variabel som `auto` gir gammel oppførsel
- Spesifisert variabel som noe annet blir parset som aws region.
Ikke så mye å teste egentlig. 
Kan se at man ikke får den støyete ec2 metadata fetching failed (e.l) feilmeldingen lokalt.
> Add properties for AWS S3 regions, rather than auto-detecting

- image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
- image-api/src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala
Fikser NDLANO/Issues#3703 for nye bilder
Også må vi oppdatere metadataen på alle eksisterende bilder, feks med `s3cmd`:
`s3cmd --recursive modify --add-header="Cache-Control:max-age=2592000" s3://test.images.2.ndla/`
> image-api: Add `cache-control` metadata when uploading images

- image-api/src/main/scala/no/ndla/imageapi/controller/RawController.scala
Fixes NDLANO/Issues#3719
Brukte lenger tid enn jeg tør å innrømme på å forstå at jeg hadde en feil i oppsettet mitt som gjorde at jeg testa feil ting :sweat_smile: 
Men etter jeg fiksa det så var ikke denne oppgaven så veldig vanskelig.
La inn funksjonalitet for å ikke feile dersom resizing eller cropping feiler, og heller bare logge feilen.
Blir litt mer robust, men kanskje litt vanskeligere å oppdage resizing feil uten å lese logger, hva tenker dere?
> #3719: Skip resizing svg-images even with weird fileextensions

- article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
- article-api/src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- article-api/src/test/scala/no/ndla/articleapi/TestData.scala
- article-api/src/test/scala/no/ndla/articleapi/TestEnvironment.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- article-api/src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/validation/ContentValidator.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ReadService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/resources/html-rules.json
- validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
- validation/src/main/scala/no/ndla/validation/HtmlTagRules.scala
- validation/src/main/scala/no/ndla/validation/TagRules.scala
- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/main/scala/no/ndla/validation/TextValidator.scala
- validation/src/main/scala/no/ndla/validation/ValidationRules.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
- validation/src/test/scala/no/ndla/validation/HtmlTagRulesTest.scala
- validation/src/test/scala/no/ndla/validation/HtmlValidatorTest.scala
- validation/src/test/scala/no/ndla/validation/UnitSuite.scala
Nytt format på valideringskode. Støtter html i utvalgte embed-attributter.
På litt sikt kan vi legge inn feks validering av url og epost i valideringskoden ved å spesifisere regex i validation-feltet.
> Rebuild embed validation

- article-api/src/main/scala/no/ndla/articleapi/controller/SwaggerDocControllerConfig.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SwaggerDocControllerConfig.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/SwaggerDocControllerConfig.scala
Må bruke tapir syntax/dsl for å lage `EndpointInput` typen når det er mer enn én part.
> article-api: Fix swagger mount point :^)

- draft-api/src/main/scala/no/ndla/draftapi/controller/FileController.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/FileStorageService.scala
Sets threshold before streaming file to disk rather than memory to avoid heap ooms when uploading big files :^)
Ser ut til å løse problemet med opplastning av filer. Jeg prøvde med en på 279MB og det gikk fra å ikke fungere til å fungere :smile:
> draft-api: Set file threshold for `FileController`

- frontpage-api/src/main/scala/no/ndla/frontpageapi/db/migration/V9__add_missing_fields.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/db/migration/V9__add_missing_fields_Test.scala
Noen subjectpages feiler i test etter nyeste migreringen (Feks [198](https://api.test.ndla.no/frontpage-api/v1/subjectpage/198)).
Dette er fordi den forrige migreringen brukte litt utdaterte klasser for å parse det som lå i databasen (Påkrevd `mobileImageId` i `BannerImage` feks).
Denne PR'en legger til en migrering som ikke bruker noen case classer men bare bruker circe for å manipulere json :smile:
> frontpage-api: Add V9 migration that does the same as V8

- search-api/src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala
- search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/Node.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
RelevanceId fra taksonomi er riktignok en optional, men den returneres _alltid_!
Og i ndla-frontend sjekkes det om relevance === 'Tilleggstoff' så dette er første steg i å ikkje trenge denne sjekken.
Dette er også et steg i å fjerne behovet for relevance som tekst i søkekonteksten, men heller utlede fra id. Id endres aldri uansett.
> Handle all relevanceId as string, and return in api

- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Fixes NDLANO/Issues#3776
Setter ansvarlig ved kloning. Dette er fordi at når du kloner en artikkel så får du ikkje lov å lagre før du har oppdatert taksonomi. Men siden oppdatering av taksonomi lagrer artikkelen i bakkant, og lagringa feiler fordi ansvarlig ikkje er satt, så blir ikkje lagreknapp i taksonomiblokk grønn. Så derfor trur brukere av ed at alt feila, og lager ny kopi!
Test:
Sjekk at ansvarlig blir satt ved kloning av artikkel.
> Sets responsible to the cloner

- article-api/src/main/resources/no/ndla/articleapi/db/migration/V44_SlugsToLowercase.sql
- article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- article-api/src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- draft-api/src/main/resources/no/ndla/draftapi/db/migration/V51__SlugsToLowercase.sql
- draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- draft-api/src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
Fixes NDLANO/Issues#3785
Gjør at alle slugs lagres i lowercase og vi konverterer alle oppslag til lowercase før oppslag i databasen.
Tror ikke det trenger endringer noen annen plass.
> #3785: Lowercase slugs in draft-api & article-api

- concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/Concept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableConcept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptSearchService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchServiceTest.scala
Fixes https://github.com/NDLANO/Issues/issues/3791
Glemte å sjekke assignees så jeg stjal denne fra @rauboti :sweat_smile: 
Legger til et uindeksert felt `domainObject` til `SearchableConcept` på samme måte som vi har på images.
Legger også til indeksert felt for `gloss` for søkbarhet.
> concept-api: Add gloss to index and summary

- validation/src/main/resources/embed-tag-rules.json
https://trello.com/c/3ZHUqmuT/84-kan-ikke-redigere-alt-tekst-for-bilde-som-settes-i-boks-for-ekstern-ressurs
Satt kun opp `imageid` som dependant. Blir det riktig at jeg ikke lister opp `data-alt` i `mustCoexistWith` på de andre attributene? Den er tross alt ikke required.
> Add data-alt attribute to iframe embed

- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/FilmFrontPageData.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/NewOrUpdatedFilmFrontPageData.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/FilmFrontPageData.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ConverterService.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/TestData.scala
NDLANO/Issues#3821
Legger på støtte for å lagre informasjonsartikkel på ndla-film-sida.
> Add support for saving an article-id to info article

- learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V34__AddShareNameToUser.sql
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Folder.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/MyNDLAUser.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/MyNDLAUser.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Legger til mulighet for å dele navn på eiger av mappe. Dette medfører at vi begynner å lagre displayname fra feidebruker på brukerobjektet i basen. Navnet lagres kun dersom brukeren faktisk velger å dele navnet sitt.
NDLANO/Issues#3814
> Share name on folder

- article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- audio-api/src/main/scala/no/ndla/audioapi/repository/AudioRepository.scala
- concept-api/src/main/scala/no/ndla/conceptapi/repository/DraftConceptRepository.scala
- concept-api/src/main/scala/no/ndla/conceptapi/repository/PublishedConceptRepository.scala
- draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- image-api/src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala
Vet ikke om dette påvirket andre ting enn bilder siden jeg ikke eeegentlig har opplevd problemet før.
Men var en bug som gjorde at et bilde kunne dukke opp på flere sider i en dump så jeg la til sortering på alle dump endepunktene.
Kan testes ved å se at `/intern/dump/<type>` endepunktene fungerer som forventet.
> Order dumps by id

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
https://github.com/NDLANO/Issues/issues/3840
> Expanded shared folder query

- myndla/src/main/scala/no/ndla/myndla/model/domain/Folder.scala
Builds on https://github.com/NDLANO/backend/pull/346
Åpner sjekken for isClonable, slik at eier av mappe kan klone en mappe selv om den ikke delt.
> Clone unshared folder if owner

- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ConfigController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/UserController.scala
I stedet for at finavnet skal brukes.
> Makes swagger-doc consistent  with other tapir apis

- validation/src/main/resources/embed-tag-rules.json
For å kunne lagre kampanjeblokk uten lenke
> Url in campaignblock should not be required

- concept-api/src/main/scala/no/ndla/conceptapi/service/WriteService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
Kom frem et ønske her: https://trello.com/c/rhzCoGCo/596-versjonslogg-i-forklaringer-gloser om at vi også skal oppdatere versjonslogg når forklaring/glose oppdateres. Kan sikkert vente med å merge til vi har et eget trello-kort på det!
> concept-api: Update editorNotes when concept data is changed

- image-api/src/main/scala/no/ndla/imageapi/controller/RawController.scala
- image-api/src/main/scala/no/ndla/imageapi/service/ImageConverter.scala
- image-api/src/test/scala/no/ndla/imageapi/service/ImageConverterTest.scala
Vi sender inn prosenter med opp til 15 desimaler, og disse konverteres til ints. Derfor mister vi nøyaktighet. Dette gjør at crop blir meir korrekt. 
Neste steg blir kanskje å innføre støtte for både prosent og pixler ved cropping.
> Drop converting to int to get correct crops

- common/src/main/scala/no/ndla/common/model/domain/ArticleContent.scala
- common/src/main/scala/no/ndla/common/model/domain/ArticleMetaImage.scala
- common/src/main/scala/no/ndla/common/model/domain/Author.scala
- common/src/main/scala/no/ndla/common/model/domain/Description.scala
- common/src/main/scala/no/ndla/common/model/domain/Introduction.scala
- common/src/main/scala/no/ndla/common/model/domain/RequiredLibrary.scala
- common/src/main/scala/no/ndla/common/model/domain/Tag.scala
- common/src/main/scala/no/ndla/common/model/domain/Title.scala
- common/src/main/scala/no/ndla/common/model/domain/VisualElement.scala
- common/src/main/scala/no/ndla/common/model/domain/article/Article.scala
- common/src/main/scala/no/ndla/common/model/domain/article/Copyright.scala
- common/src/main/scala/no/ndla/common/model/domain/package.scala
- validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
- validation/src/main/scala/no/ndla/validation/HtmlTagRules.scala
- validation/src/main/scala/no/ndla/validation/ValidationRules.scala
Encoder/Decoder's for `Either` typen er litt rare med `circe` så vi må bruke semi-auto (Mennesker på internett mener dette er bedre uansett, men jeg syns det er litt mye boilerplate).
Dette fikser feilen med a publisering ikke fungerer dersom artikkelen har `RelatedContent`.
Kan testes ved å prøve å publisere 34626 fra test :smile:
> common: Add semi-auto encoders and decoders to `domain.Article`

- article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleIntroduction.scala
- article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleTitle.scala
- article-api/src/main/scala/no/ndla/articleapi/service/ConverterService.scala
- article-api/src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- article-api/src/test/scala/no/ndla/articleapi/TestData.scala
- article-api/src/test/scala/no/ndla/articleapi/TestEnvironment.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
- article-api/src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/TestEnvironment.scala
- draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
- validation/src/main/resources/embed-tag-rules.json
- validation/src/main/scala/no/ndla/validation/TextValidator.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
Legger til støtte for inlinetekster i tittel og ingress. Legger på html-versjoner av tittel og introduction i api-artikkel.
> Expand allowed html

- build.sbt
- concept-api/src/main/scala/no/ndla/conceptapi/ComponentRegistry.scala
- concept-api/src/main/scala/no/ndla/conceptapi/controller/InternController.scala
- concept-api/src/main/scala/no/ndla/conceptapi/integration/TaxonomyApiClient.scala
- concept-api/src/main/scala/no/ndla/conceptapi/integration/model/TaxonomySubject.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/domain/Sort.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableConcept.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/IndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptIndexService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/TestEnvironment.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchServiceTest.scala
- search-api/src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala
- search-api/src/main/scala/no/ndla/searchapi/model/domain/Sort.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search/src/main/scala/no/ndla/search/model/SearchableLanguageValues.scala
@katrinewi sa vi trengte å sortere på de feltene som finnes i arbeidslisten i ed.
Returnerer feltene for drafts:
`resourceTypeName` tilsvarer `Innholdstype`
`parentTopicName` tilsvarer `Emnetilhørlighet`
`primaryRootName` tilsvarer `Primærfag`
Sortering med henholdsvis `resourceType`, `parentTopicName`, og `primaryRoot`.
> Sorting by worklist parameters

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/ConfigController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/StatsController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/UserController.scala
> Mark endpoints moved to myndla-api as deprecated.

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/StatsController.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/StatsControllerTest.scala
Testa lokalt og med curl funker det med `curl -L` for å få data fra myndla-api. Via swagger funka det uten endringer.
> Make users fetch stats from myndla-api

- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
- myndla/src/main/scala/no/ndla/myndla/model/api/SingleResourceStats.scala
- myndla/src/main/scala/no/ndla/myndla/model/domain/FolderResource.scala
- myndla/src/main/scala/no/ndla/myndla/repository/FolderRepository.scala
- myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala
- project/myndlaapi.scala
- typescript/myndla-api.ts
Relates to https://github.com/NDLANO/Issues/issues/3943
Legger til et endepunkt som ser sånn ca sånn her ut:
```http
GET /myndla-api/v1/stats/favorites/resource/30543?resourceType=article
```
Som svarer med noe som ligner på dette
```json
{
"favourites": 14
}
```
> myndla-api: Add stats endpoint for resources

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/TestData.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
- myndla/src/main/scala/no/ndla/myndla/model/api/Folder.scala
- myndla/src/main/scala/no/ndla/myndla/model/domain/Copyable.scala
- myndla/src/main/scala/no/ndla/myndla/model/domain/Resource.scala
- myndla/src/main/scala/no/ndla/myndla/repository/FolderRepository.scala
- myndla/src/test/scala/no/ndla/myndla/TestData.scala
- myndla/src/test/scala/no/ndla/myndla/service/FolderConverterServiceTest.scala
- myndla/src/test/scala/no/ndla/myndla/service/FolderReadServiceTest.scala
- myndla/src/test/scala/no/ndla/myndla/service/FolderWriteServiceTest.scala
Fixes https://github.com/NDLANO/Issues/issues/3949
> Convert folder `resourceType` to enum

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/parameters/DraftSearchParams.scala
Fikser beskrivelser på doc på input-parameteret på post endepunktet.
Skjønner ikke helt hvorfor vi trenger dette, men det funker i alle fall :shrug:
> search-api: Fix input body params

- network/src/main/scala/no/ndla/network/tapir/NonEmptyString.scala
- network/src/test/scala/no/ndla/network/tapir/NonEmptyStringTest.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/parameters/DraftSearchParams.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Siden vi tryner om vi sender inn en tom streng så tenker jeg vi kan være litt tydeligere med typingen :smile:
> search-api: Use `NonEmptyString` as `query`

- search-api/src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Vi slutta å hente disse i fjor i ndla-frontend, og no er dei også borte fra graphql-api.
> Removing legacy fields from context

- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- article-api/src/main/scala/no/ndla/articleapi/controller/InternController.scala
- audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
- common/src/main/scala/no/ndla/common/model/api/CommaSeparatedList.scala
- concept-api/src/main/scala/no/ndla/conceptapi/controller/ConceptControllerHelpers.scala
- concept-api/src/main/scala/no/ndla/conceptapi/controller/DraftConceptController.scala
- concept-api/src/main/scala/no/ndla/conceptapi/controller/PublishedConceptController.scala
- draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/BaseImageController.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV3.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/InternController.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Når vi bruker `sttp.tapir.model.CommaSeparated` direkte, ender vi opp med en streng som default-verdi når vi bruker `.default`.
Dette resulterer i at Swagger tror det skal være ett element med en tom streng i forespørselen.
Å pakke det inn i en `Option` lar oss ha en default-verdi `None`, og den implicit classen gjør overgangen mellom
Option[CommaSeparated[...]] og CommaSeparated[...] ganske enkel, sånn at det blir lett å gå tilbake om [denne](https://github.com/softwaremill/tapir/issues/3581) blir løst.
> Make `CommaSeparatedList` to work around empty default values

- concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/StateTransitionRules.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/WriteService.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/StateTransitionRulesTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Jeg tenker vi kan droppe denne `IO`-wrappingen med mindre vi skal begynne å bruke `IO` "på-ordentlig". Sånn den er nå så gjør den bare at vi må spesial-håndtere context-variabler uten at vi faktisk får noe nytte av det.
> Avoid some unnecessary `IO` wrapping

- draft-api/src/main/scala/no/ndla/draftapi/service/FileStorageService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
Path til fil i artikkel mangler "resources". Er dette ok eller vil det kunne gå i beina på oss i etterkant?
> Add part to path to fix file-upload.

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedEndpoint.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedProvider.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedEndpointTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedProviderTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedServiceTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/ProviderServiceTest.scala
Tidligere så lente vi oss på at `ndlaClient` brukte json4s sin magiske `camelization` av keys.
> oembed-proxy: Fix deserialization of providers.json

- common/src/main/scala/no/ndla/common/model/domain/learningpath/EmbedUrl.scala
embedType blei sendt ut av apiet som IFrame og ikkje iframe. Dette fikser det.
Det er en mulighet for at det er andre steder tilsvarende kan ha skjedd.
Fixes NDLANO/Issues#3989
> Override toString to fix api

- article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- article-api/src/main/scala/no/ndla/articleapi/ComponentRegistry.scala
- article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
- article-api/src/main/scala/no/ndla/articleapi/integration/FrontpageApiClient.scala
- article-api/src/main/scala/no/ndla/articleapi/model/domain/Cachable.scala
- article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
- article-api/src/test/scala/no/ndla/articleapi/TestEnvironment.scala
- article-api/src/test/scala/no/ndla/articleapi/model/CachableTest.scala
- article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
- common/src/main/scala/no/ndla/common/configuration/BaseProps.scala
- common/src/main/scala/no/ndla/common/model/api/FrontPage.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FrontPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ConverterService.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ReadService.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/WriteService.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/controller/FrontPageControllerTest.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/model/api/FrontPageTest/FrontPageTest.scala
- project/frontpageapi.scala
Fixes https://github.com/NDLANO/Issues/issues/3946
Dersom vi vil ha en penere url enn `https://api.test.ndla.no/article-api/v2/articles/utlysninger/rss.xml` så kan vi nok lage en redirect i proxy elller api-gateway (Avhengig av hva vi vil ha).
PR'en ser litt større ut enn den er, siden jeg endte med å flytte `api.FrontPage` fra `frontpage-api` til `common` for å kunne gjenbruke typen i `article-api` :smile:
> Generate RSS feed for frontpage article menu

- validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
Urlen i testklassen ligger lagra i apiet i dag, så dette må til for å kunne redigere artikkelen.
> Støtter $ og ; i urler for å ta høgde for gapminder.

- myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V10__subcategories.sql
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ArenaController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/integration/nodebb/NodebbModels.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Category.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/CategoryBreadcrumb.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/CategoryWithTopics.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/NewCategory.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Category.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ConverterService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ImportService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- typescript/types-backend/myndla-api.ts
Legger til støtte for underkategorier
Brødsmulestier er nok ikke det mest optimaliserte i verden, men jeg går ut i fra at ytelsen ikke blir veldig påvirket pga mengden data. Lokal benchmark viste <10ms forskjell i alle fall.
> myndla-api: Add support for subcategories

- draft-api/src/main/scala/no/ndla/draftapi/model/domain/StateTransition.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/SideEffect.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Utvider `SideEffect` til å bli en klasse med navn og funksjon for å enklere kunne debugge.
Legger også på et debuggingsflagg som bare er enablet i en flaky test.
Forhåpentligvis så vil dette hjelpe oss når vi får den flaky testen til å være flaky igjen :shrug:
> draft-api: Rewrite sideEffects in attempt to locate the flakyness

- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/FolderController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
Trengte visst litt mer data! Returnerer hele resource-objektet istedenfor her
> Return full resource for /recent

- common/src/main/scala/no/ndla/common/model/domain/ResourceType.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/FolderController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
- Legger til mulighet for å filtrere ut resource types
**Er det noe lurt jeg må gjøre for å få til at return-typen(ResourceType) oppdateres basert på eventuelle exclude-filtre man sender inn?**
> myndla-api: Add query param to filter on resource types in /recent

- audio-api/src/main/scala/no/ndla/audioapi/controller/HealthController.scala
- audio-api/src/test/scala/no/ndla/audioapi/controller/HealthControllerTest.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/HealthController.scala
- image-api/src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala
- network/src/main/scala/no/ndla/network/tapir/NdlaTapirMain.scala
- network/src/main/scala/no/ndla/network/tapir/Routes.scala
- network/src/main/scala/no/ndla/network/tapir/TapirHealthController.scala
https://github.com/NDLANO/deploy/pull/749
Health controllers now include:
- `/health/liveness` : Returns 200 if the application is alive
- `/health/readiness`: Returns 200 if the application is alive and ready to serve requests
- `/health`          : Same as `/health/liveness/`
> Split health checks into multiple endpoints

- article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/articleapi/ArticleApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/draftapi/DraftApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/learningpathapi/LearningpathApiClientTest.scala
Sjekka databasen og såg at en artikkel som feila på dette endepunktet hadde et innslag med null i document-feltet. Dette vil fikse den iden samt eventuelle tilsvarende. 
Denne feiler i dag https://api.test.ndla.no/article-api/v2/articles/external_ids/60733
> Ignores docs with null object because of failed imports.

- network/src/main/scala/no/ndla/network/model/HttpRequestException.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/OEmbedProxyController.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedServiceComponent.scala
Denne gjør litt småting:
- Implementerer retries for å forsøke å omgå `GOAWAY` sakene fra ndla-frontend/ingress/proxy vet ikke hvor det kommer fra
- 410 når ndla-frontend returnerer 410
- 422 istedetfor 501 når vi ikke støtter en provider.
> Fix some oembed-proxy 5xx errors

- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
Etter å ha sett de [forbedrede loggene](https://github.com/NDLANO/backend/actions/runs/8938510461/job/24552783936?pr=464#step:7:62) når flake skjedde, så tror jeg at denne mocken er problemet.
Vet ikke egentlig hvorfor, men har sett `thenReturn` lage trøbbel vs `doReturn` tidligere, så tenkte å prøve samme fiksen her.
> Attempt fixing test-flake by using `doAnswer` over `thenAnswer`

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
Ser at vi får noen 500 feil fordi provideren matcher uten schema, også finner den ingen endepunkter for schemaet.
Sånn _eegentlig_ så burde vi sikkert ikke tillate å lagre url'er med http, men jeg ser youtube provideren oppgraderer de til https uansett, så for akkurat denne så er det nok uproblematisk 😄
> oembed-proxy: Support http urls for youtube

- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
Dette `.copy` kallet i `toDomainArticle` har plaget meg litt.
Selvom jeg syns egentlig lesbarheten er bedre med så blir det veldig lett å overse denne funksjonen når man legger til nye felter.
> draft-api: Stop using copy in `toDomainArticle`

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Så vi fikk 500 feil på dette i prod.
Går ut i fra at vi gjør et eller annet feil et annet sted også som gjør at denne feiler, men vi burde i alle fall fikse feilmeldingen.
Kan vel kanskje hende det er pga utgått token også.
> search-api: Return correct error when requesting illegal availability

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedServiceComponent.scala
Prøver å fikse `GOAWAY` problemene med http 1.1
> oembed-proxy: Use http 1.1 when fetching oembeds

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedEndpoint.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedProvider.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedEndpointTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/model/OEmbedProviderTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedServiceTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/ProviderServiceTest.scala
Fjerner muligheten til å lage endpoints uten `url`, og returnerer 422 dersom noen spør om en url som ikke er valid i provideren istedenfor 500.
> oembed-proxy: Fix generic server error

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/TaxonomyFiltering.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala
Filtrering på context-types gir kun treff på kontekster. Men vi har redefinert parameteret til å være læringsressurser, og det er uavhengig av om den finnes i struktur eller ikkje.
Dette løser problemet der favorittmerka læringsstier som er fjerna fra struktur forsvinner fra delte mapper.
> Filter learningresources independent of taxonomy

- common/src/main/scala/no/ndla/common/model/domain/ResourceType.scala
Blei aldri tatt i bruk og er erstatta av mappe-lenker.
> Not needed anymore

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedProvider.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedConverterService.scala
- oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedConverterServiceTest.scala
- oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/ProviderServiceTest.scala
Ser ut som vi har prøvd å støtte dette tidligere men ikke helt fått det til.
Dette fikser :smile: 
Kan testes med å forsøke å embed'e en spilleliste:
/oembed-proxy/v1/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLJBPGA24dsn_HLSn6bmA8ajn-9AVGCWje
> oembed-proxy: Fix youtube playlist support

- myndla-api/src/main/scala/no/ndla/myndlaapi/model/api/Stats.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/controller/StatsControllerTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderReadServiceTest.scala
Guttorm ville ha et format på stats som var lettere å lese inn i airbyte. Legger på en map på formatet
```
"favourites": {
"learningpath": 452,
"image": 37,
"audio": 2,
"multidisciplinary": 26,
"article": 8223,
"folder": 1,
"video": 13,
"concept": 10
}
```
> Add alternative display of favourited resources. Expand test.

- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
Nok en karturl som ikkje blei godkjent. 
Basert på https://documentation.mapp.com/1.0/en/url-encoding-and-what-characters-are-valid-in-a-uri-36147771.html har eg lagt til `[]()` og * i tillegg til ,.
> Add support for , [ ] ( ) * in urls.

- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Post.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- project/myndlaapi.scala
- typescript/types-backend/myndla-api.ts
Dette fikser feilen vi hadde med `circular reference error" typene med litt omdirigering.
Litt hacky, men det fungerer :smile:
> myndla-api: Add hacky trait wrapper to avoid scala-tsi recursion bug

- myndla-api/src/main/scala/no/ndla/myndlaapi/model/api/ArenaUser.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Flag.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Post.scala
Retur typen til en reply ble til  `{ Post: ArenaPost }`. La merke til at Folder hadde encoder og decoders så implemnterte det samme for Post.
> Added decoder and encoder to Arena models

- oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
Disse feilene er jo brått ikke vår feil (derfor vi sender de til brukeren), så jeg tenker vi kan logge de som info.
> oembed-proxy: Dont log errors we pass along to the user as error

- validation/src/main/resources/embed-tag-rules.json
Related to https://github.com/NDLANO/Issues/issues/4165
> validation: Make `data-image-id` optional for `key-figure` embeds

- article-api/src/main/scala/no/ndla/articleapi/model/api/NDLAErrors.scala
- article-api/src/main/scala/no/ndla/articleapi/service/search/SearchService.scala
- audio-api/src/main/scala/no/ndla/audioapi/model/api/Error.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/model/api/NDLAErrors.scala
- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/SearchService.scala
- image-api/src/main/scala/no/ndla/imageapi/model/api/Error.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/SearchService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/ErrorHelpers.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/search/SearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/model/api/Error.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search/src/main/scala/no/ndla/search/Elastic4sClient.scala
- search/src/main/scala/no/ndla/search/NdlaSearchException.scala
- Slutter å feile dersom feide sier access denied
- Tar med mer informasjon i søke requests som feiler
- Ser disse relativt ofte med ingen informasjon i, så tenkte vi kunne hive med den faktiske elasticsearch requesten som feiler også for å få litt mer informasjon.
- Logger faktisk feilene dersom indeksering feiler
> Reduce error noise in search-api + extend indexing errors

- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Topic.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/database/Compiled.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ConverterService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/ArenaRepositoryTest.scala
Forsøk på å legge til voteCount slik at typene blir riktige i GraphQL også. Nødvendige for å kunne støtte reaksjoner på TopicCard i nytt design.
KAN alternativt utvides til å også ha voteCount til categories også, men sida det ikke er noen direkte støtte for det i GraphQL (uten at vi trikser inn og summerer sjøl), er det ikke lagt inn enda.
> Add voteCount to topic

- validation/src/main/resources/html-rules.json
- validation/src/main/scala/no/ndla/validation/TagRules.scala
Skal brukes til å vise fargede versjoner av `FramedContent` og `blockquote` basert på artikkeltype (hvis man velger at de skal være farget).
> chore: support data-variant on divs and blockquotes

- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
Introduserer en valideringspath som slår inn dersom man _bare_ har redigert editor felter (`notes`, `comments`, `revisionMeta`).
Dersom vi treffer denne pathen validerer vi bare editor feltene og ikke resten av artikkelen.
Usecasen er å ikke validere ansvarlig dersom vi bare skal oppdatere notes når vi oppdaterer kvalitetsvurdering.
> draft-api: Add editorial validation path

- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/LearningPath.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Vi sletter koblinger til stier som har blitt kopiert dersom status endres bort fra publisert. Men det vil sei at dersom en sti endres og repubiseres så mistes koblinga for kopiene. Eg synes det gir mest meining om koblinga slettes først dersom original sti slettes, altså får status Deleted.
Grunnen til at eg fant dette var mange stier som var oppdatert i vår sjølv om eiger ikkje hadde logga på på fire år.
> Only disconnect copies when path is deleted

- article-api/src/main/scala/no/ndla/articleapi/db/migration/V53__StripHideBylineFromSize.scala
- article-api/src/test/scala/no/ndla/articleapi/db/migration/V53__StripHideBylineFromSizeTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/db/migration/V64__StripHideBylineFromSize.scala
- draft-api/src/test/scala/no/ndla/draftapi/db/migration/V64__StripHideBylineFromSizeTest.scala
Rydder opp i gamle verdier for size. I prod har vi disse variantene:
```
- ""
- "full-----hide-byline"
- "full-hide-byline--hide-byline"
- "full-------hide-byline"
- "full"
- "full---hide-byline"
- "fullbredde"
- "full--"
- "full-hide-byline"
- "fullwidth"
- "medium"
- "full--------hide-byline"
- "full-"
- "full------hide-byline"
- "fullwidth-hide-byline"
- "medium--hide-byline"
- "full--hide-byline"
- "full---"
- "xsmall"
- "full----hide-byline"
- "medium-hide-byline--hide-byline"
- "small"
- "medium-hide-byline"
```
> Converts size attribute for image embeds

- article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
- article-api/src/main/scala/no/ndla/articleapi/db/migration/V54__RemoveStrongFromTitle.scala
- article-api/src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- article-api/src/test/scala/no/ndla/articleapi/db/migration/V54__RemoveStrongFromTitleTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
- draft-api/src/main/scala/no/ndla/draftapi/db/migration/V65__RemoveStrongFromTitle.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/db/migration/V65__RemoveStrongFromTitleTest.scala
Fjerner lagra strong-tags fra tittel på artikler.
> Remove strong from titles

- common/src/main/scala/no/ndla/common/model/domain/learningpath/LearningPath.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/db/migration/V39__MadeAvailableForThePublished.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/LearningPathV2.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Fixes https://github.com/NDLANO/Issues/issues/4223
> learningpath-api: Adds `madeAvailable` field to learningpaths

- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
Fixes https://github.com/NDLANO/Issues/issues/4227
Er det ikke litt uheldig egentlig?
Vil jo fremdeles publiseres så artiklene er jo fortsatt "live"?
Antar vi ikke vil ha motsatt også (at vi ikke setter visible = false på avpublisering)?
> Stop updating taxonomy metadata on publish

- common/src/main/scala/no/ndla/common/model/domain/ResourceType.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/FolderController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderWriteService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
- project/myndlaapi.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- typescript/types-backend/myndla-api.ts
Må til for å kunne favorittmerke emner.
+ litt scala 3 formatering
> Add topic to possible favorite types

- network/src/main/scala/no/ndla/network/tapir/NonEmptyString.scala
- network/src/test/scala/no/ndla/network/tapir/NonEmptyStringTest.scala
Fixes https://github.com/NDLANO/Issues/issues/4233
Fikser det ved å ikke tillate whitespace only strenger i `NonEmptyString`. Navnet på `NonEmptyString` sier ikke noe om at bare whitespace ikke er lov, men jeg _antar_ at det aldri vil være nyttig for oss så vi løser det der tror jeg :smile:
> search-api: Stop returning 500 on whitespace only queries

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Vi trenger at disse ikke er hemmelige for at ndla-frontend skal få lov til å hente de :nerd_face:
> search-api: Stop requiring permissions for grep search

- concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/search/SearchService.scala
- language/src/main/scala/no/ndla/language/Language.scala
- search-api/src/main/scala/no/ndla/searchapi/ComponentRegistry.scala
- search-api/src/main/scala/no/ndla/searchapi/SearchApiProperties.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
- search-api/src/main/scala/no/ndla/searchapi/controller/parameters/GetSearchQueryParams.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestEnvironment.scala
Etter mye røring så har jeg skjønt hvordan vi kan gjøre dette, og det ble ikke _sååå_ krise engang.
Dette bør la oss ha mer enn 22 query parametere i fremtiden :nerd_face:
> search-api: Use a case class for query parameters for GET `/search-api/v1/search`

- article-api/src/main/scala/no/ndla/articleapi/validation/ContentValidator.scala
- article-api/src/test/scala/no/ndla/articleapi/TestData.scala
- article-api/src/test/scala/no/ndla/articleapi/validation/ContentValidatorTest.scala
- common/src/main/scala/no/ndla/common/model/domain/Disclaimer.scala
- common/src/main/scala/no/ndla/common/model/domain/article/Article.scala
- common/src/main/scala/no/ndla/common/model/domain/draft/Draft.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleDTO.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/DisclaimerDTO.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/NewArticleDTO.scala
- draft-api/src/main/scala/no/ndla/draftapi/model/api/UpdatedArticleDTO.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/TestData.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
fixes https://github.com/NDLANO/Issues/issues/4246
> draft-api/article-api: Add disclaimer field

- article-api/src/main/scala/no/ndla/articleapi/db/migrationwithdependencies/V55__SetHideBylineForImagesNotCopyrighted.scala
- draft-api/src/main/scala/no/ndla/draftapi/db/migrationwithdependencies/V66__SetHideBylineForImagesNotCopyrighted.scala
Dette fikser en logisk feil i forrige versjon av migreringa. Det som skjedde då var at om hidebyline var satt så blei ikkje bildeid sendt til imageid, noko som førte til at hidebyline blei satt til false for bilder som var satt inn med hidebyline=true fordi images.find ikkje har bildet som sjekkes. 
Dette henter litt fleire bilder fra image-api, men oppdaterer kun dei som ikkje har verdien satt allerede.
> Only set hideByline if not already set

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
Så det var litt krøll i loggene så tenker disse kan få lov til å være 409 :nerd_face:
> learningpath-api: Allow returning http 409 from PATCH endpoints

- .github/workflows/typescript-generate.yml
- search-api/src/main/scala/no/ndla/searchapi/model/api/grep/GrepResultDTO.scala
- search-api/src/test/scala/no/ndla/searchapi/model/api/grep/GrepResultDTOTest.scala
- typescript/types-backend/search-api.ts
Virker som scala-tsi sin generering av sealed typer ikke er stabil som gjør at vi lager en evig loop med actions.
Tror dette vil bli stabilt nå, ved å generere unionen selv fremfor å lene oss på scala-tsi sin macro.
> Fix unstable typescript generation of `GrepResultDTO`

- article-api/src/main/scala/no/ndla/articleapi/db/migration/V55__RemoveArticleIdFromUUDisclaimer.scala
- article-api/src/test/scala/no/ndla/articleapi/db/migration/V55__RemoveArticleIdFromUUDisclaimerTest.scala
- draft-api/src/main/scala/no/ndla/draftapi/db/migration/V66__RemoveArticleIdFromUUDisclaimer.scala
- draft-api/src/test/scala/no/ndla/draftapi/db/migration/V66__RemoveArticleIdFromUUDisclaimerTest.scala
- validation/src/main/resources/embed-tag-rules.json
- validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala
Fjerner article-id fra uu-disclaimer, tror dette er alt som trengs? 🤔
> Remove article-id from uu disclaimer

- common/src/main/scala/no/ndla/common/model/api/myndla/MyNDLAUserDTO.scala
- common/src/main/scala/no/ndla/common/model/domain/myndla/MyNDLAUser.scala
- common/src/main/scala/no/ndla/common/model/domain/myndla/MyNDLAUserDocument.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderConverterService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ImportService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/UserService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/TestData.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/controller/ArenaControllerTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/controller/FolderControllerTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/ArenaRepositoryTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderConverterServiceTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderReadServiceTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/UserServiceTest.scala
- search-api/src/main/scala/no/ndla/searchapi/service/StandaloneIndexing.scala
> myndla-api: Add `arenaAccepted` flag on myndla users

- common/src/main/scala/no/ndla/common/model/api/myndla/MyNDLAUserDTO.scala
- common/src/main/scala/no/ndla/common/model/domain/myndla/MyNDLAUser.scala
- common/src/main/scala/no/ndla/common/model/domain/myndla/MyNDLAUserDocument.scala
- myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V18__remove_shareName.sql
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderConverterService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/ImportService.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/service/UserService.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/TestData.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/controller/ArenaControllerTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/controller/FolderControllerTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/ArenaRepositoryTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderConverterServiceTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderReadServiceTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/service/UserServiceTest.scala
- typescript/types-backend/myndla-api.ts
relatert til https://trello.com/c/QBFwlYTp/1217-oppdatert-min-profil-side
> Remove shareName

- image-api/src/main/scala/no/ndla/imageapi/service/search/ImageIndexService.scala
- image-api/src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
- search/src/main/scala/no/ndla/search/model/SearchableLanguageValues.scala
Merket at ganske mange bilder ikke har editornotes.
La oss ta med `createdBy` og `updatedBy` for å få litt bedre søkeresultater :nerd_face:
> image-api: Include `createdBy` & `updatedBy` in searchable users

- article-api/src/test/scala/no/ndla/articleapi/service/search/ArticleSearchConverterServiceTest.scala
- article-api/src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
- audio-api/src/test/scala/no/ndla/audioapi/service/search/SearchConverterServiceTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/search/ArticleSearchServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/search/GrepCodesSearchServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/search/TagSearchServiceTest.scala
- image-api/src/test/scala/no/ndla/imageapi/service/search/TagSearchServiceTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/articleapi/ArticleApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/draftapi/DraftApiClientTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/learningpathapi/LearningpathApiClientTest.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/LearningPathAndStepCreationTests.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/LearningPathIndexServiceTest.scala
- tapirtesting/src/main/scala/no/ndla/tapirtesting/TapirControllerTest.scala
@MaPoKen fant en bug hvor noen læringssteg fikk `seqNo` under 0.
Denne PR'en fikser så det ikke lenger er mulig ved å oppdatere hele `seqNo` lista hver gang (~~Vi gjør allerede alle databasekallene så jeg tenker det er like greit~~ stryk det, jeg løy, men jeg tenker uansett at de få kallene der ved skriving er verdt robustheten :smile: ).
Gjør også sånn at man får 404 om man prøver å slette et slettet steg.
> learningpath-api: Fix seqNo bug

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
Vet ikke hvorfor jeg la inn at man måtte være admin eller ndla-bruker for å kopiere denne tidligere, men jeg mistenker at det bare ikke var så gjennomtenkt :nerd_face:
> learningpath-api: Allow everyone with permissions to copy learningpaths

- concept-api/src/main/scala/no/ndla/conceptapi/ComponentRegistry.scala
- concept-api/src/main/scala/no/ndla/conceptapi/db/migration/V22__SplitTags.scala
- concept-api/src/main/scala/no/ndla/conceptapi/db/migrationwithdependencies/V23__SubjectNameAsTags.scala
- concept-api/src/test/scala/no/ndla/conceptapi/db/migration/V22__SplitTagsTest.scala
- concept-api/src/test/scala/no/ndla/conceptapi/db/migrationwithdependencies/V23__SubjectNameAsTagsTest.scala
Fixes https://github.com/NDLANO/issues/issues/4282
Denne har to migreringer:
- En som splitter opp `:`-separerte nøkkelord
- En som fetcher fag fra taksonomi og legger på fag-navnet som tags.
> Convert concept subjectids to tags

- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
- scalatestsuite/src/main/scala/no/ndla/scalatestsuite/BufferedLogAppender.scala
Gjør sånn at `/learningpath-api/v2/learningpaths/ids/` kan kalles av alle.
Men dersom man ikke er eier eller har redigeringstilgang på en privat sti så blir den ikke med i resultatet.
> learningpath-api: Open `ids` endpoint to allow everyone to fetch

- network/src/main/scala/no/ndla/network/model/CombinedUser.scala
Since the constructor of the sealed trait runs before the child constructor the fields are `null` when the `isMyNDLAUser` field is calculated.
Lets fix this by making it a function instead of a calculated value.
> network: Use `def` to avoid racecondition `null`

- search-api/src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummaryDTO.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableLearningPath.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/TestData.scala
- search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
- search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
- search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableLearningPathTest.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
Trengs for at aggregeringer på ressurstype ikkje skal gi alt for masse treff. Dette setter en primærkontekst på søkeobjektet, slik at det går an å aggregere på context.resourceTypes.id og kun få en per treff.
> Add default context to searchables

- search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
Default er at usynlige kontekster filtreres ut, men for editorial-søket trenger vi at alt er med.
> Must send isVisible=false for unpublished tax to get ed-search correct.

- common/src/main/scala/no/ndla/common/model/domain/language/OptLanguageFields.scala
- common/src/test/scala/no/ndla/common/model/domain/LanguageFieldsTest.scala
Fikser en bug i draft-api hvor vi trigget status-endringer fordi man sammenlignet med `NotWanted`
Så om man hadde:
disclaimer:
- "nb" -> "hei"
- "en" -> "hello"
og oppdaterte til
disclaimer:
- "nb" -> "hei"
- "en" -> "hello"
- "nn" -> `NotWanted`
Så ble det ansett som en endring.
> common: Make `OptLanguageFields` compare without `NotWanted` values

- search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
Støtter lisens-parameter for gruppert søk. Måtte bruke GetSearchQueryParam fordi det blei for mange parameter i tuple om eg la til license.
> Use GetSearchQueryParam for grouped search

- common/src/main/scala/no/ndla/common/model/domain/frontpage/MovieTheme.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FilmPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/FilmFrontPageDTO.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/FilmFrontPage.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/repository/FilmFrontPageRepository.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ConverterService.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/service/WriteService.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/TestData.scala
- frontpage-api/src/test/scala/no/ndla/frontpageapi/service/WriteServiceTest.scala
> Add endpoints for deleting language of subject page and film front page

- validation/src/main/scala/no/ndla/validation/HtmlTagRules.scala
- validation/src/main/scala/no/ndla/validation/TagValidator.scala
- validation/src/main/scala/no/ndla/validation/TextValidator.scala
- validation/src/test/scala/no/ndla/validation/UnitSuite.scala
Lagring av noen artikler feiler fordi data-url har whitespace. Og siden den har fleire språkversjoner går det ikkje an å lagre den i det heile tatt. Bør sikkert kjøre trim ved lagring også.
> Gjør at validering av url i embed ikkje feiler ved lagring.

- article-api/src/main/scala/no/ndla/articleapi/ComponentRegistry.scala
- article-api/src/test/scala/no/ndla/articleapi/repository/ArticleRepositoryTest.scala
- audio-api/src/main/scala/no/ndla/audioapi/ComponentRegistry.scala
- audio-api/src/main/scala/no/ndla/audioapi/repository/AudioRepository.scala
- concept-api/src/main/scala/no/ndla/conceptapi/ComponentRegistry.scala
- concept-api/src/test/scala/no/ndla/conceptapi/TestData.scala
- concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
- database/src/main/scala/no/ndla/database/DBMigrator.scala
- draft-api/src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/ComponentRegistry.scala
- image-api/src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
- image-api/src/test/scala/no/ndla/imageapi/controller/InternControllerTest.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/ComponentRegistry.scala
Since we now start the applications when generating typescript we need to be able to build the component registry without connecting to a database.
This patch moves the actual database connecting to `DBMigrator` and make the `dataSource` member lazy so it isn't accessed before needed.
> Make `dataSource` lazy to avoid initialization before needed

- learningpath-api/src/main/scala/no/ndla/learningpathapi/db/migration/V44__AddTargetAndRelToAnchors.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/TextValidator.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/db/migration/V44__AddTargetAndRelToAnchorsTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/validation/TextValidatorTest.scala
Her trengs det også en migrering som legger på `target="_blank"` og `rel="noopener noreferrer"` på anchor tags i description på læringsstisteg @jnatten  😇
> Update validation: Allow target and rel attributes on anchor

- search-api/src/main/scala/no/ndla/searchapi/model/grep/GrepBundle.scala
- search-api/src/main/scala/no/ndla/searchapi/model/grep/GrepElement.scala
- search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableNode.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/NodeIndexService.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
- search-api/src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala
Oversetter grepkode for kompetansemålsett til å ta med verdier for tilhørende kompetansemål. Dette gjør at du kan få treff på fag kun dersom et kompetansemål er i settet som er satt på faget.
> Add grepkodes for nodes.

- common/src/main/scala/no/ndla/common/model/api/UpdateOrDelete.scala
- network/src/main/scala/no/ndla/network/tapir/SwaggerControllerConfig.scala
- project/Dependencies.scala
Etter tapir [v1.11.21](https://github.com/softwaremill/tapir/releases/tag/v1.11.21) så kan vi bruke `nullable` attributtet på tapir-schema'et istedenfor å hacke oss rundt det med postprossesering.
> Remove hacky schema post processing

- project/Module.scala
Dette gjorde at bloop kræsja (som brukes av metals), så om noen ville prøve seg på metals så ble det en fryktelig dårlig opplevelse.
(Ikke se på klokkeslettet på denne PR'en)
> Fix log4j sbt reference

- learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- network/src/main/scala/no/ndla/network/ApplicationUrl.scala
Forhindrer dobbel id på metaurl
Fixes NDLANO/Issues#4349
> Do not use ApplicationUrl for metaurl

- typescript/types-backend/learningpath-api-openapi.ts
- typescript/types-backend/scripts/generate-openapi.ts
@Lekesoldat lærte meg at felter med default verdier blir default generert til å være required.
Dette kunne sikkert blitt veldig irriterende i fremtiden :nerd_face:
> typescript: Generate fields with default values as optional

- search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
- search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
https://trello.com/c/5oir3xYY/1343-legge-til-filter-p%C3%A5-utdanningsprogram-s%C3%B8keside
Indekserer programme kontekster, men filtrerer de ut på vei ut av apiet.
Dette gjør at `subjects` filtered fungerer med programme id'er.
Dette gjør at indekseringsprosessen bruker en god del mer minne [så vi må øke `Xmx` på cronjob'en](https://github.com/NDLANO/deploy/pull/1091).
> search-api: Begin indexing programme contexts

- draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
- draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
- draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/SideEffect.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
- draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
- draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
- draft-api/src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
- draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
- integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
Klarte ikke finne disse flaggene i ed eller i logger så jeg syns vi kan fjerne de.
Gjør oppdateringslogikken litt lettere å henge med på :smile:
> draft-api: remove unused import and external id update flags

- article-api/src/main/scala/no/ndla/articleapi/MainClass.scala
- audio-api/src/main/scala/no/ndla/audioapi/MainClass.scala
- common/src/main/scala/no/ndla/common/logging/package.scala
- concept-api/src/main/scala/no/ndla/conceptapi/MainClass.scala
- database/src/main/scala/no/ndla/database/DBMigrator.scala
- database/src/main/scala/no/ndla/database/DBUtility.scala
- draft-api/src/main/scala/no/ndla/draftapi/MainClass.scala
- frontpage-api/src/main/scala/no/ndla/frontpageapi/MainClass.scala
- image-api/src/main/scala/no/ndla/imageapi/MainClass.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/MainClass.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/MainClass.scala
Merket at disse ble logget som feil da jeg prøvde å klone en mappe som ikke fantes.
Tenker at feilloggingen burde skje i error handleren i controlleren fremfor i denne funksjonen dersom det er noe faktisk galt 😄 (Og det skjer jo egentlig allerede, så dette tilførte bare støy).
La også på logging for utførte migreringer sånn at det er litt enklere å se hva som faktisk skjer når migreringer kjører.
> stop logging rollback exceptions as errors by default

- .github/workflows/ci.yaml
- common/src/main/scala/no/ndla/common/Warmup.scala
- common/src/main/scala/no/ndla/common/configuration/BaseProps.scala
- log4j2.yaml
- network/src/main/scala/no/ndla/network/tapir/NdlaTapirMain.scala
- network/src/main/scala/no/ndla/network/tapir/Routes.scala
- network/src/main/scala/no/ndla/network/tapir/TapirHealthController.scala
Implementerer graceful shutdowns.
Dvs at applikasjonene ikke vil stoppe med en gang de får en sigterm som tidligere, men vil feile readiness proben sin og deretter vente til alle aktive requests er ferdig å prosessere.
Dette vil i teorien gjøre at vi ikke vil avlive requests som pågår som gjør at utbytting av kubernetes noder og nedskaleringer vil lage mindre (sannsynligvis ingen) "hikke".
Tror dette er en god ide, kanskje ektra god etter vi oppgraderer ECK operatoren så elasticsearch også gjør noe lignende 😄
> Graceful shutdowns

- learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/ErrorHandling.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/TestEnvironment.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Litt usikker på logikken for å verifisere at en har flere språkversjoner av et steg. Tok inspirasjon fra draft, der vi sjekker mengden titler. Men her klarte jeg helt fint å få to forskjellige embed-URL'er med kun én tittel.
Hvordan skal vi håndtere sletting av språkversjon av læringssti? Skal vi da også slette alle steg som har språkvarianter på det slettede språket?
> feat: delete learning step language

- log4j/test/log4j2-test.yaml
- testbase/src/main/scala/no/ndla/testbase/TestSuiteLoggingSetup.scala
Gjør dette på samme måte som vi gjør under faktisk kjøring for å unngå en warning i testkjøringer
> programatically trigger log4j shutdown hook in tests

- modules/DockerComponent.mill
Dette krevde en liten hack siden https://mill-build.org/mill/contrib/docker.html ikke hadde noen native støtte for å endre _bare_ entrypointet så da tar jeg bare å redigerer den siste linja i dockerfile'n.
By default så bruker de sånn syntax: `ENTRYPOINT ["java", ...]` og det støtter ikke shell expansion 🤷 
Vi kunne sikkert også i teorien tatt i bruk disse `JAVA_TOOL_OPTIONS` variablene som noen jvm'er støtter, men det virker litt som det ikke oppfordres til det.
> mill+docker: _actually_ expand `JAVA_OPTS` during startup

- article-api/src/main/scala/no/ndla/articleapi/controller/ControllerErrorHandling.scala
- audio-api/src/main/scala/no/ndla/audioapi/controller/ControllerErrorHandling.scala
- audio-api/src/main/scala/no/ndla/audioapi/controller/HealthController.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/TranscriptionService.scala
- audio-api/src/main/scala/no/ndla/audioapi/service/WriteService.scala
- concept-api/src/main/scala/no/ndla/conceptapi/controller/ControllerErrorHandling.scala
- draft-api/src/main/scala/no/ndla/draftapi/controller/ControllerErrorHandling.scala
- image-api/src/main/scala/no/ndla/imageapi/controller/ControllerErrorHandling.scala
- image-api/src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/ControllerErrorHandling.scala
- myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ControllerErrorHandling.scala
Når DI-oppsettet ble refaktorert, ble lazy-loadede `DataSource` ikke lenger lastet lazily. Dette førte til at kjøring av `generateTypescript` feilet på CI for alle komponenter som krevde miljøvariabler ved oppstart.
Fikser problemet ved å sende inn dataSource og noen andre avhengigheter som en [by-name-parameter](https://docs.scala-lang.org/tour/by-name-parameters.html) der de tidligere ble brukt ved oppstart.
> fix: props eager loading, but lazy failing

- .github/workflows/formatting.yml
- .gitignore
- dependency-graph/README.md
- dependency-graph/src/Main.scala
- dependency-graph/src/ScalaFileParser.scala
- modules/DefaultOptions.mill
Denne gjør at vi slipper å ha semanticdb filer ved siden av kildekodefilene 🛩️ 
Dere kan kjøre denne for å fjerne de tror jeg `git clean -fd "*.semanticdb"`
> refactor(ci): utilize `semanticDbData` from mill

- learningpath-api/src/main/scala/no/ndla/learningpathapi/db/migration/V54__ConvertIntroductionSteps.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/db/migration/V54__ConvertIntroductionStepsTest.scala
This migration only covers steps that satisfy the following criteria:
- The step is of type "INTRODUCTION"
- It is the first step of a learning path
- It does not have any embedUrls
- It does not have introductions and descriptions.
Har ikke bestemt meg for om vi skal veksle mellom å godta beskrivelse og introduksjon. Det er to sånn ca to gamle stier som har introduksjon i test, resten er fra Min NDLA. De fra Min NDLA har vel ikke `type: "INTRODUCTION"` uansett, så de vil ikke prosesseres. Hva tenker folket?
> feat: migrate introduction steps to learningpath introduction

- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
Fikk beskjed om at rekkefølge på mapper endra seg og fant at vi sorterer på id og ikkje rank noen plasser. Gir vel mest meining å sortere på rank der vi har det?
> Make sorting subfolders consistent

- learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/UpdatedLearningStepV2DTO.scala
- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Vi har en del ressurssteg som har tittel, selv om de ikke nødvendigvis trenger det lenger. Man ender da ofte opp med steg som dette: https://test.ndla.no/r/verktoykassa---for-elever/bloff-med-statistikk/d9709169df/9382. Med denne endringen vil folk få muligheten til å nullstille dette i ED.
> feat: allow deletion of step title

- myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
- myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/FolderTest.scala
Ved sletting av ressurs, sorteres alle søsken til ressursen på nytt. Dette skjer ved at FolderResources hentes fra basen, den aktuelle ressursen fjernes, og resten sorteres i den rekkefølgen dei ligger i lista. Men siden postgres returnerer rekkefølge avhengig av sist oppdatert så lenge du ikkje har ORDER BY så risikerer du at ressursene dine plutselig er hulter til bulter! Dette omgår problemet ved å eksplisitt sortere ressursene i mappa.
> Make sure children is fetched sorted before deleting

- article-api/src/main/resources/no/ndla/articleapi/db/migration/V63__RemoveTeacherAvailability.sql
- draft-api/src/main/resources/no/ndla/draftapi/db/migration/V77__RemoveTeacherAvailability.sql
Ganske mye availability-relatert kode i backend som kanskje er greit å beholde i tilfelle NDLA vil ha dette tilbake igjen. Migrerer bort resterende teacher-verdier istedenfor.
> chore: migrate away teacher availability

- learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
Hvis man tidligere hadde en sti på flere språk som inneholdt et steg med kun ett språk feilet slettingen av språket
> fix: delete learning path language when no steps match language

- learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/LearningPathValidator.scala
- learningpath-api/src/test/scala/no/ndla/learningpathapi/validation/LearningPathValidatorTest.scala
Slutter å forhindre at offentlige læringsstier kan kopieres til Min NDLA. 
Dette har sluppet gjennom sprekkene tidligere, fordi isMyNDLAOwner ikkje blei satt som det skulle, men etter siste endringene blokkeres det.
> Stop preventing copying of learningpaths
