draft-api/src/main/scala/no/ndla/draftapi/model/domain/StateTransition.scala
draft-api/src/main/scala/no/ndla/draftapi/model/domain/package.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala

Litt mer kode enn den opprinnelige til @Jonas-C men vil kanskje skalere slightly bedre :shrug:

Make argument to allow ignoring roles passed in `required` function

---

audio-api/src/main/scala/no/ndla/audioapi/service/ConverterService.scala
audio-api/src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala

Passer på at sletting av språkversjoner sletter alle språkfelt.

Sletter alle språkfelt for audio.

---

audio-api/src/main/scala/no/ndla/audioapi/service/ValidationService.scala
audio-api/src/test/scala/no/ndla/audioapi/service/ValidationServiceTest.scala
concept-api/src/main/scala/no/ndla/conceptapi/validation/ContentValidator.scala
concept-api/src/test/scala/no/ndla/conceptapi/validation/ContentValidatorTest.scala
draft-api/src/main/scala/no/ndla/draftapi/validation/ContentValidator.scala
draft-api/src/test/scala/no/ndla/draftapi/validation/ContentValidatorTest.scala
image-api/src/main/scala/no/ndla/imageapi/service/ValidationService.scala
image-api/src/test/scala/no/ndla/imageapi/service/ValidationServiceTest.scala

Fixes https://github.com/NDLANO/Issues/issues/2935
Lagt på is inntil videre, men satser på at den ikke vil ende opp altfor langt bak dersom den tas videre.

2935 Added validation for correlation between license usage and copyright holders

---

validation/src/main/resources/embed-tag-rules.json

NDLANO/Issues#2988
Legger til ny url for støtta embeds.

Added new iframe src

---

concept-api/src/main/scala/no/ndla/conceptapi/model/api/Concept.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
concept-api/src/test/scala/no/ndla/conceptapi/TestData.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala

Denne fikser så automatisk-delpublisering ikke feiler en lagring OG at den kun forsøker å delpublisere de feltene som har endret seg.

Fix problems with automatic partial publishing

---

draft-api/typescript/index.ts
project/draftapi.scala

Autogenerer nye typer for typescript

Converting old enums to enumeratum library

---

draft-api/typescript/index.ts
project/draftapi.scala

Legger til `IUploadedFile` og `INewAgreement`

Generate more types in draft api

---

concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableConcept.scala
concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableCopyright.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptIndexService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptIndexService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchServiceTest.scala

Legger til copyright i søkeresultat henta fra indeks. Har ikkje lagt til søk etter innholdet i copyright, kun lagring og henting.

Adds limited copyright field to search result.

---

validation/src/main/resources/embed-tag-rules.json

Mikroendring. Ny url for iframe embed.

New iframe url

---

concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
concept-api/src/main/scala/no/ndla/conceptapi/model/search/SearchableConcept.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/DraftConceptIndexService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/PublishedConceptIndexService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala

Legger til `source` i index'ene
@Jonas-C needs this for good

concept-api: Index `source` field for concepts

---

article-api/src/main/scala/db/migration/V35__AddDataTypeToIframeEmbed.scala
article-api/src/test/scala/db/migration/V35__AddDataTypeToIframeEmbedTest.scala
draft-api/src/main/scala/db/migration/V35__AddDataTypeToIframeEmbed.scala
draft-api/src/test/scala/db/migration/V35__AddDataTypeToIframeEmbedTest.scala
validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/main/scala/no/ndla/validation/TagRules.scala
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

NDLANO/Issues#3002
Legger til rette for å lagre ekstra info i iframe-embed.
Usikker på om eg bør legge data-type direkte under required eller om den bør være under optional. Den skal fungere som et flagg som forteller om url i embed skal vises i en iframe eller som ei lenke som sett på https://trello.com/c/IvYvttIJ/999-design-sidemal-for-applikasjoner

Add support for saving title, caption and image-id

---

article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala

Gjør så vi ikke får hull i pagineringen (Og samtidig fikser count'en) slik at search-api indekseringen ikke tuller det til 😄

article-api: Make dumping articles and the article count consistent

---

.github/workflows/article-api_release.yml
.github/workflows/audio-api_release.yml
.github/workflows/concept-api_release.yml
.github/workflows/draft-api_release.yml
.github/workflows/frontpage-api_release.yml
.github/workflows/image-api_release.yml
.github/workflows/learningpath-api_release.yml
.github/workflows/oembed-proxy_release.yml
.github/workflows/search-api_release.yml

Ny versjon av kubectl krever at vi fikser litt på config så låser den til den gamle frem til bruker nyere versjon

Fixes release by locking kubectl

---

README.md
image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
image-api/src/main/scala/no/ndla/imageapi/model/api/ImageMetaSummary.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
image-api/src/test/scala/no/ndla/imageapi/controller/ImageControllerV2Test.scala
image-api/typescript/index.ts
project/imageapi.scala

NDLANO/Issues#2846
Legger til billedtekst i søkeresultatet.

Adds caption to search results for images

---

image-api/src/main/scala/no/ndla/imageapi/service/ConverterService.scala
image-api/src/test/scala/no/ndla/imageapi/service/ConverterServiceTest.scala

Fixes NDLANO/Issues#3111
Kan testes ved å sjekke at fil-dimensjoner blir oppdatert når man patcher en image-fil :^)

#3111: Update image dimensions when updating image file

---

search-api/src/main/scala/no/ndla/searchapi/controller/NdlaController.scala
search-api/src/main/scala/no/ndla/searchapi/model/domain/draft/RevisionMeta.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala

Ser at serialiseringa ikkje fungerer som det skal uten id i revisionmeta.

Adding id parameter to be able to serialize correctly

---

draft-api/src/main/scala/no/ndla/draftapi/integration/LearningpathApiClient.scala
draft-api/src/main/scala/no/ndla/draftapi/integration/SearchApiClient.scala
draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
draft-api/src/test/scala/no/ndla/draftapi/TestData.scala
draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala

Fixes NDLANO/Issues#3131
Checks if article is in use before unpublish.
Updates error message with title of blocking learningpath or article.

Sjekker om artikkel er i bruk før avpublisering

---

audio-api/src/main/scala/no/ndla/audioapi/service/ValidationService.scala
image-api/src/main/scala/no/ndla/imageapi/service/ValidationService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/TextValidator.scala
project/Dependencies.scala
project/articleapi.scala
project/audioapi.scala
project/draftapi.scala
project/imageapi.scala
project/learningpathapi.scala
project/oembedproxy.scala
project/searchapi.scala
project/validationlib.scala
validation/src/main/scala/no/ndla/validation/TextValidator.scala

PR'en oppdaterer litt div biblioteker og fikser noe smått breaking changes.

Security bumps

---

audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
audio-api/src/main/scala/no/ndla/audioapi/controller/SeriesController.scala
audio-api/src/main/scala/no/ndla/audioapi/model/api/SearchParams.scala
audio-api/src/main/scala/no/ndla/audioapi/model/api/SeriesSearchParams.scala
audio-api/src/main/scala/no/ndla/audioapi/model/domain/SearchSettings.scala
audio-api/src/main/scala/no/ndla/audioapi/model/domain/SeriesSearchSettings.scala
audio-api/src/main/scala/no/ndla/audioapi/service/search/AudioSearchService.scala
audio-api/src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
audio-api/src/main/scala/no/ndla/audioapi/service/search/SeriesSearchService.scala
audio-api/src/test/scala/no/ndla/audioapi/TestData.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/AudioSearchServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/SeriesSearchServiceTest.scala

#3190: Audio & Podcast search fallback :⁾

---

audio-api/src/main/scala/no/ndla/audioapi/model/domain/AudioMetaInformation.scala

Commit signed off by the gracious bokkak 😎

Adds missing `JavaTimeSerializers.all`

---

article-api/src/main/scala/articleapi/db/migration/V35__AddDataTypeToIframeEmbed.scala
article-api/src/main/scala/articleapi/db/migration/V37__AddDataTypeToExternalEmbed.scala
draft-api/src/main/scala/draftapi/db/migration/V35__AddDataTypeToIframeEmbed.scala
draft-api/src/main/scala/draftapi/db/migration/V38__AddDataTypeToExternalEmbed.scala
validation/src/main/resources/embed-tag-rules.json
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

NDLANO/Issues#3195
Legger til type på external-embed. DRY så det holder!

Add type to external-embed.

---

audio-api/src/main/scala/no/ndla/audioapi/controller/SeriesController.scala

audio-api: JavaTimeSerializers in `SeriesController`

---

learningpath-api/src/main/resources/learningpathapi/db/migration/V18__RemoveFavoriteFieldFromDocument.sql
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Folder.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Content.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala

Fjerner isFavorite flagg fra folders og fra databasen. Fjerner også logikken som stoppa brukere å slette favoritt mapper

Remove favorite flag from folders

---

common/src/main/scala/no/ndla/common/implicits/package.scala
image-api/src/main/resources/imageapi/db/migration/V14__DeleteExtraImageFileData.sql
image-api/src/main/scala/imageapi/db/migration/V15__OneImageFileRowForEachLanguage.scala
image-api/src/main/scala/no/ndla/imageapi/model/NDLAErrors.scala
image-api/src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala
image-api/src/test/scala/no/ndla/imageapi/TestData.scala
image-api/src/test/scala/no/ndla/imageapi/service/WriteServiceTest.scala
project/commonlib.scala

Fixes NDLANO/Issues#3198
Kan testes ved å sjekke at overskriving av eksisterende bildefiler og opplasting av bildefiler på nye språk fungerer som forventet. :smile:

#3198: Fix image replacement uploading

---

project/Dependencies.scala
project/build.properties

Klarte ikke finne noen grunner til å ikke bumpe til siste versjon 😄

Bump sbt version

---

article-api/src/test/scala/no/ndla/articleapi/service/search/ArticleSearchServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/AudioSearchServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/SeriesSearchServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/TagIndexServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/TagSearchServiceTest.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/search/DraftConceptSearchServiceTest.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/search/PublishedConceptSearchServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/AgreementSearchServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/ArticleSearchServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/GrepCodesIndexServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/GrepCodesSearchServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/TagIndexServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/search/TagSearchServiceTest.scala
image-api/src/test/scala/no/ndla/imageapi/service/search/ImageSearchServiceTest.scala
image-api/src/test/scala/no/ndla/imageapi/service/search/TagSearchServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
scalatestsuite/src/main/scala/no/ndla/scalatestsuite/UnitTestSuite.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala

Move all `blockUntil` to scalatestsuite

---

scalatestsuite/src/main/scala/no/ndla/scalatestsuite/IntegrationSuite.scala

Fant ut at jeg var lei av å vente på disse tingene lokalt når jeg har mulighet til å kjøre de fra før av.
Ingen garantier for at tester ikke kan påvirker hverandre her, men det _bør_ testene tenke på selv 😄

Support `NDLA_SKIP_CONTAINER_SPAWN` flag

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/ConfigController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/FeideUser.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/FeideUser.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/UserRole.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
network/src/main/scala/no/ndla/network/clients/FeideApiClient.scala

Fixes https://github.com/NDLANO/Issues/issues/3291
Begrenser skrivetilgang for studenter under eksamner.
Skal vi tillate brukere å slette mapper/ressurser/konto under eksamen?
Skal vi tillate sortering?

Write lock during exams

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/ConfigController.scala
project/learningpathapi.scala

Glemte å legge til nye typen i typescript

add ConfigMetaRestricted typescript type

---

project/learningpathapi.scala

Genererer FeideUser typescript typen

generate FeideUser typescript type

---

article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
audio-api/src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/FrontpageApiProperties.scala
image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedProxyProperties.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedSwagger.scala
search-api/src/main/scala/no/ndla/searchapi/SearchApiProperties.scala

NDLANO/Issues#3340
Oppdaterer swagger-doc

Update swagger doc for all apis

---

image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV3.scala
image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala

image-api: Return V3 type for V3 patch endpoint

---

article-api/src/main/scala/no/ndla/articleapi/MainClass.scala
article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala
article-api/src/main/scala/no/ndla/articleapi/repository/ArticleRepository.scala
article-api/src/main/scala/no/ndla/articleapi/service/ReadService.scala
article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
draft-api/src/main/scala/no/ndla/draftapi/MainClass.scala
draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ReadService.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala

The endpoint have not been used in prod for more than a year
Veldig trygg kode å slette!

Removing unused tags cache.

---

audio-api/src/main/scala/no/ndla/audioapi/service/search/SearchService.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/AudioSearchServiceTest.scala

Fixes NDLANO/Issues#3349
Ser ut som vi har glemt å fjerne noe gammel kode her når det har blitt oppdatert :shrug:

Fix fallback search for audio-api

---

article-api/src/main/scala/no/ndla/articleapi/controller/InternController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/InternController.scala
search-api/src/main/scala/no/ndla/searchapi/controller/InternController.scala
search-api/src/main/scala/no/ndla/searchapi/integration/SearchApiClient.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala

Har savnet dette mange ganger når man prøver å finne ut hvorfor en enkel artikkel feiler indeksering :smile:

Single article-reindexing

---

search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala

Fixes bug fetching to little data.
Heng sammen med https://github.com/NDLANO/taxonomy-api/pull/161
Henter også topics og resources med paginering. Fikse også at før blei kun maks 10 sider henta.

Fetches resources and nodes with pages

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/StatsController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2Test.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/StatsControllerTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponentIntegrationTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala

Lar deg hente ut læringsstier med id som parameter. Krever roller i learningpath-api slik at kun innlogga bruker i ed kan hente ut disse.

Ids endpoint for learningpaths

---

project/Dependencies.scala
scalatestsuite/src/main/scala/no/ndla/scalatestsuite/IntegrationSuite.scala

Fikser opp i snyk-feil
Semi-depends on https://github.com/NDLANO/deploy/pull/447 (Dvs, jeg tipper den funker uten, men er ikke vits å ta noen sjanser :smile:)

Bump dependencies for security :^)

---

project/Dependencies.scala

Det var et aldri så lite problem hvor logging ikke fungerte pga noe versjonsmismatch. Dette skal fikse problemet :^)

Bump logging libraries

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala

Kan endelig bruke userrepo for å hente ut antall brukere.

use user repo for folder stats

---

article-api/src/main/scala/no/ndla/articleapi/controller/ArticleControllerV2.scala

article-api: Fix doc return-type for external-ids

---

article-api/src/main/scala/no/ndla/articleapi/ArticleApiProperties.scala
article-api/src/main/scala/no/ndla/articleapi/integration/DraftApiClient.scala
article-api/src/main/scala/no/ndla/articleapi/integration/SearchApiClient.scala
audio-api/src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
common/src/main/scala/no/ndla/common/configuration/BaseProps.scala
concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/FrontpageApiProperties.scala
image-api/src/main/scala/no/ndla/imageapi/ImageApiProperties.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/LearningpathApiProperties.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedProxyProperties.scala
search-api/src/main/scala/no/ndla/searchapi/SearchApiProperties.scala

Move some shared variables to common

---

draft-api/src/main/scala/no/ndla/draftapi/controller/InternController.scala

Dette vil nok ikke ha så stor innvirkning i miljøene, men lokalt så er forskjellen ganske stor.
Vi burde nok uppe limits for indeksering også. 
Grunnen til at draft-api er _så_ mye tregere enn alle andre er at cpu-limits er mye lavere i tillegg til at den har 4 indekser å opprette.
Siden 3 av indeksene bygges opp fra artikler så kunne vi nok spart en del tid på å merge de sammen inn i `ArticleIndexService`, men jeg stemmer for å sjekke ut hvordan det funker med høyere limits først for å holde kompleksiteten nede :smile:

draft-api: Perform reindexing in parallel

---

search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/settings/MultiDraftSearchSettings.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/settings/SearchSettings.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

Forsideartikler er ikkje læringsressurser, så vi må ha mulighet til å kunne søke kun på disse. Det gir meining både fra ed og fra ndla.no, gitt at en kan lage eget søk for forsideartikler.

Search frontend articles

---

audio-api/src/main/scala/no/ndla/audioapi/AudioApiProperties.scala
audio-api/src/main/scala/no/ndla/audioapi/controller/SeriesController.scala
audio-api/src/main/scala/no/ndla/audioapi/db/migration/V16__AddSeriesRSSField.scala
audio-api/src/main/scala/no/ndla/audioapi/model/api/NewSeries.scala
audio-api/src/main/scala/no/ndla/audioapi/model/api/Series.scala
audio-api/src/main/scala/no/ndla/audioapi/model/domain/Series.scala
audio-api/src/main/scala/no/ndla/audioapi/service/ConverterService.scala
audio-api/src/test/scala/no/ndla/audioapi/TestData.scala
audio-api/src/test/scala/no/ndla/audioapi/db/migration/V16__AddSeriesRSSFieldTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/WriteServiceTest.scala
audio-api/src/test/scala/no/ndla/audioapi/service/search/AudioSearchServiceTest.scala

Adds flag making it possible to turn off rss for series.
Fixes NDLANO/Issues#3334

Adds check for audio:admin for series

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/MyNDLAUser.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala

Fixes https://github.com/NDLANO/Issues/issues/3412

students are no longer able to share folders

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Stats.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/StatsControllerTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala

Kan testes mot lokal database. 
Kopierte db fra test til lokal og fikk 31 favorittfag.

Adding number of favorited subjects to stats

---

search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala

Paginert henting var for å unngå timeout på api-gateway, men vi har slutta å gå via gateway så dette er en raskere måte å hente alt av data på.

Goes back to use old way of fetching taxonomy in bulk

---

validation/src/main/resources/embed-tag-rules.json

Fixes https://github.com/NDLANO/Issues/issues/3397

add optional field 'data-title' to iframe

---

search-api/src/main/scala/no/ndla/searchapi/SearchApiProperties.scala

Gjør det mulig å tweake bulkstørrelse på henting av artikler

Bigger bulk

---

frontpage-api/src/main/scala/no/ndla/frontpageapi/FrontpageApiProperties.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/Error.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/repository/SubjectPageRepository.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ReadService.scala

Fixes https://github.com/NDLANO/Issues/issues/3446

add new ids endpoint in frontpage-api

---

draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleSummary.scala
draft-api/src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala

https://www.bible.com/bible/1932/LUK.11.9-13.FBV

draft-api: Return `updated` field in draft search

---

concept-api/src/main/scala/no/ndla/conceptapi/controller/NdlaController.scala
concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala

:dragon: trengte dette :smile:

concept-api: Add `responsible` to search-response

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/main/scala/no/ndla/validation/TagRules.scala

relates to https://github.com/NDLANO/Issues/issues/3511

Validation:Added-new-embed-type

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

Gjør om på kontaktblokk feltene da de har blitt forandra siden start. Oppdaterte navnene til variablene så de er mer beskrivende. Samt la til flere felter som er optional

Valdiation: Added updated tags for contactblock

---

learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V29__AddDescriptionFieldToFolders.sql
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/Folder.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Copyable.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Folder.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/FolderRepositoryTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala

Partly fixes https://github.com/NDLANO/Issues/issues/3495
Legger `description` feltet på Folder.

Description for folders

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/FolderController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/FolderRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala

Fixes: https://github.com/NDLANO/Issues/issues/3531

Fix folder shared timestamp bug

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/resources/html-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

La til støtte for Grid på DIV elementet.

Added validation for new grid plugin

---

concept-api/src/main/scala/no/ndla/conceptapi/db/migration/V14__TrimConceptTitle.scala
concept-api/src/test/scala/no/ndla/conceptapi/db/migration/V14__TrimConceptTitleTest.scala

Fixes https://github.com/NDLANO/Issues/issues/3552

concept-api: add migration, trim whitespace from titles

---

draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala

Kommentarer skal ikkje slettes når du bruker Lagre som ny.

Keeps comments when saving new version manually

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/resources/html-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

Grids skal ha mulighet for border i følge designet.

Validation: Added border tag to div

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/resources/html-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

Bakgrunnsfargen på frontpageartikler vil være forskjellige fra default og grid må kunne styles med full hvit bakgrunn

Validation: Added background to grid color

---

common/src/main/scala/no/ndla/common/errors/NDLAErrors.scala
frontpage-api/src/main/resources/no/ndla/frontpageapi/db/migration/V7__RemoveTopicalAndCategories.sql
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FrontPageController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/InternController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/ErrorHelpers.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/FrontPage.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/api/FrontPageData.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/Errors.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/FrontPage.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/FrontPageData.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/repository/FrontPageRepository.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ConverterService.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ReadService.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/service/WriteService.scala
frontpage-api/src/test/scala/no/ndla/frontpageapi/TestEnvironment.scala
frontpage-api/src/test/scala/no/ndla/frontpageapi/controller/FrontPageControllerTest.scala
frontpage-api/src/test/scala/no/ndla/frontpageapi/model/api/FrontPageTest/FrontPageTest.scala
network/src/main/scala/no/ndla/network/tapir/auth/Scope.scala
project/frontpageapi.scala
typescript/frontpage-api.ts

fixes https://github.com/NDLANO/Issues/issues/3582
Kan testes GET og POST endepunkter.

Support for new frontpage type

---

validation/src/main/resources/html-rules.json

Grid har forskjellig størrelse på gap mellom forside artikler og vanlig artikler. Legger til data-size så vi kan styre størrelsen

Added data-size to div

---

article-api/src/main/scala/no/ndla/articleapi/db/migration/V42__MigrateOldToNewGrepCodes.scala
article-api/src/test/scala/no/ndla/articleapi/db/migration/V42__MigrateOldToNewGrepCodesTest.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migration/V49__MigrateOldToNewGrepCodes.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V49__MigrateOldToNewGrepCodesTest.scala

Fixes NDLANO/Issues#3606
Kan testes ved å se at grepcodes migreres riktig (se spreadsheet på trello i issue-kortet) :smile:

#3606: Add migrations to convert old grepcodes to new

---

integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/learningpathapi/LearningpathApiClientTest.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableLearningPath.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableLearningStep.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/LearningPathIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableLearningPathTest.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableLearningStepTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/DraftIndexServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/LearningPathIndexServiceTest.scala
search/src/main/scala/no/ndla/search/TestUtility.scala

Har alltid irritert meg at dette ikke er typesikkert på et eller annet vis så tenkte det var lurt å lage noen tester for det (Siden det virker som faktisk typesikkerhet er vanskelig uten noen små-avanserte macroer).
Kom gjerne med motforestillinger :smile:

search-api: Adds tests for checking if every indexed field has a mapping

---

audio-api/src/test/scala/no/ndla/audioapi/controller/AudioControllerTest.scala

Litt usikker på om vi _eeegentlig_ har lyst til å gjøre det her, men det gjør i alle fall at testene i audio-api blir litt mer stabile :smile:

Add retries to `AudioControllerTest`

---

concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptSummary.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala

Fixes https://github.com/NDLANO/Issues/issues/3643

concept-api: Add `conceptType` to `ConceptSummary`

---

draft-api/src/test/scala/no/ndla/draftapi/controller/DraftControllerTest.scala
network/src/main/scala/no/ndla/network/scalatra/NdlaControllerBase.scala

Fixes https://github.com/NDLANO/Issues/issues/3651
Denne fungerte visst bare om man hadde token, men ikke rettigheter.
Fikser så denne fungerer uansett og legger til en test i draft-api.

#3651: Fix `isAllowedWithoutPermission` parameter

---

audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
audio-api/src/main/scala/no/ndla/audioapi/controller/SeriesController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FilmPageController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/FrontPageController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
network/src/main/scala/no/ndla/network/tapir/Service.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/OEmbedProxyController.scala

Lager grupper per kontroller, på samme måte som i tax.

Add grouping per service for swagger

---

search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala
search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/Node.scala

Tester å splitte opp henting av tax for å sjå om det bruker mindre minne.

Fetch resources separately

---

draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala

Relatert til NDLANO/Issues#3665

draft-api: Add `.ino` to valid file extensions

---

audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
integration-tests/src/test/scala/no/ndla/integrationtests/draftapi/articleapi/ArticleApiClientTest.scala
integration-tests/src/test/scala/no/ndla/integrationtests/searchapi/articleapi/ArticleApiClientTest.scala
network/src/main/scala/no/ndla/network/tapir/NdlaTapirMain.scala
network/src/main/scala/no/ndla/network/tapir/TapirServer.scala
project/Dependencies.scala

Virker litt som dette kanskje fungerer. 
Har gått igjennom flere ganger i alle fall :smile:

Attempt to fix integration flake

---

audio-api/src/main/scala/no/ndla/audioapi/controller/AudioController.scala
audio-api/src/main/scala/no/ndla/audioapi/controller/SeriesController.scala
network/src/main/scala/no/ndla/network/tapir/TapirErrorHelpers.scala
network/src/main/scala/no/ndla/network/tapir/auth/TokenUser.scala

Ser ut til å løse problemene med auth i swagger ui. 
Føles litt hacky, men dette gir oss i alle fall json som er veldig nært det scalata returnerte, som fungerer :shrug:

Make `TokenUser` result in `oauth2` swagger for tapir

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala

Legger til en stats på totalt antall favorittmerka fag. Usikker på om denne burde vore eget felt eller del av lista som her.

Add subjects stats

---

concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/ConverterServiceTest.scala

Var visst en bug her som gjorde at vi ikke strippa visuelt-element `ndlaembed`'s ved nye forklaringer.
Legger til tester og fikser bugen :^)

concept-api: Always strip unknown embed tag attributes in visual element

---

search-api/src/main/scala/no/ndla/searchapi/integration/TaxonomyApiClient.scala

Deploya release fra branch på test og der ligger minnebruken fint innafor grensene. Ingen OOM i første kjøring i det minste.

Tester å redusere minnebruken ved henting av tax

---

draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala

Fixes NDLANO/Issues#3754
Setter prioritertflagg til false ved publisering

Reset prioritzed when publish

---

validation/src/main/resources/embed-tag-rules.json

Legger til alt og decorative for nøkkeltall.

Add alt and is-decorative

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/UserRepository.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala

Gir meir meining å ha statistikk på antall favorittmarkeringer av fag enn antal favoritllmerka fag.

Moving number of subjects to main block.

---

validation/src/main/scala/no/ndla/validation/HtmlTagRules.scala
validation/src/main/scala/no/ndla/validation/ValidationRules.scala
validation/src/main/scala/no/ndla/validation/model/HtmlRulesFile.scala
validation/src/main/scala/no/ndla/validation/model/MathMLRulesFile.scala
validation/src/test/scala/no/ndla/validation/ValidationRulesTest.scala

Liten refaktorering for å unngå at vi mangler attributer i scala-enum'ene i fremtiden :smile:

validation: Slight refactor of the deserialization to avoid mistakes

---

frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/db/migration/V10__subjectpage_visual_element_ids.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/model/domain/VisualElement.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/service/ConverterService.scala
frontpage-api/src/test/scala/no/ndla/frontpageapi/db/migration/V10__subjectpage_visual_element_ids_Test.scala

Fixes NDLANO/Issues#3805
Noe rart har gjort at vi har fått bilde url'er i databasen for visuelt element bilder.
- Legger til validering ved oppretting/oppdatering 
- Migreringscript som fikser opp i dataen.
- Legger til validering som gjør at man ikke kan spørre om negative page/page-size parametere

#3805: Fix subjectpage visual element deserialization bug

---

draft-api/src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/integration/TaxonomyApiClientTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala

Bruker samme kode som setter node usynlig ved avpubisering, og setter noden synlig ved publisering.
ref https://trello.com/c/0BBrlfqf/1735-artikler-settes-usynlige-n%C3%A5r-de-avpubliseres-og-blir-ikke-synlige-igjen-ved-republisering

Sets node visible when publishing

---

validation/src/main/resources/embed-tag-rules.json

Validation: Add data-alt to contact-block

---

project/Module.scala
project/imageapi.scala
project/searchapi.scala

Legger til støtte for `JAVA_OPTS` for å kunne sette `-Xmx` bittelitt mer dynamisk

Allow `JAVA_OPTS` flag to docker containers

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala
validation/src/main/scala/no/ndla/validation/TagValidator.scala
validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala

NDLANO/Issues#3828
Legger på støtte for å lagre nye konfigurasjonsmuligheter.

Add data-example fields

---

image-api/src/main/scala/no/ndla/imageapi/controller/BaseImageController.scala
image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV3.scala
image-api/src/main/scala/no/ndla/imageapi/model/api/SearchParams.scala
image-api/src/main/scala/no/ndla/imageapi/model/domain/SearchSettings.scala
image-api/src/main/scala/no/ndla/imageapi/model/search/SearchableImage.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/ImageIndexService.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/ImageSearchService.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
image-api/src/test/scala/no/ndla/imageapi/TestData.scala
image-api/src/test/scala/no/ndla/imageapi/service/search/ImageSearchServiceTest.scala

Gjør det litt lettere å søke opp bilder som kan brukes som podcastbilder.

Add param to filter podcastfriendly images

---

scalatestsuite/src/main/scala/no/ndla/scalatestsuite/IntegrationSuite.scala

Vi må oppdatere postgres til 13.12, har kjørt tester i article-api, draft og integration-tests for å sjekke at alle de kjører korrekt. Fikk ingen feil.

Update postgres version to 13.12 for testing

---

audio-api/src/main/scala/no/ndla/audioapi/repository/SeriesRepository.scala
audio-api/src/main/scala/no/ndla/audioapi/service/ConverterService.scala

Sorterer podkastepisoder på created med nyeste først.

Consistent ordering of episodes on creation date

---

common/src/main/scala/no/ndla/common/model/api/draft/Comment.scala
common/src/main/scala/no/ndla/common/model/domain/draft/Comment.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migration/V53__AddSolvedToComments.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/UpdatedComment.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V53__AddSolvedToCommentsTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
typescript/draft-api.ts
typescript/search-api.ts

https://trello.com/c/UxUZJtBz/110-avsjekk-av-gule-lapper

Add solved field to comments

---

audio-api/src/main/resources/no/ndla/audioapi/db/migration/V18__Remove_alt_text.sql

Fjerner alt-tekst fra podkastinfo. Takk til copilot for sql!
NDLANO/Issues#3914

Fjerner alt-tekst fra podkastinfo

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/main/scala/no/ndla/validation/TagRules.scala
validation/src/main/scala/no/ndla/validation/TagValidator.scala
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

NDLANO/Issues#3919
Lager ny embed for å wrappe andre embeds.
Usikker på om dette er beste måten å gjøre det på, eller om det berre skal kodes som en div med noen parametre.

Add new embed

---

draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/test/scala/no/ndla/draftapi/repository/DraftRepositoryTest.scala

https://github.com/NDLANO/Issues/issues/3916
**Tror** dette skal holde!

draft-api: do not reset comments for topic article

---

myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala

Glemte visst å tenke på å markere de som lest ved fetching :smile:

myndla-api: Mark notifications as read when fetching topic with notifications

---

myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ArenaController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala

Viser seg at dette er nyttig for frontenden for å sette fokus :smile:

myndla-api: Return post instead of topic when posting

---

common/src/main/scala/no/ndla/common/DBUtil.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ArenaController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
myndla/src/main/scala/no/ndla/myndla/repository/UserRepository.scala
myndla/src/main/scala/no/ndla/myndla/service/UserService.scala

For å kunne utvide admin bruker-siden 😄

myndla-api: Add `query` and `filter-teachers` params to user endpoint

---

learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/CloneFolderTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderConverterService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderWriteService.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderConverterServiceTest.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderReadServiceTest.scala

Fixes https://github.com/NDLANO/Issues/issues/3911
Kan testes ved å se at tags skjules for andre enn eieren og ikke kommer med ved kloning :smile:

myndla-api: Avoid showing tags to non-owners

---

myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V7__allow_soft_deletion.sql
myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V8__feide_id_index.sql
myndla-api/src/main/scala/no/ndla/myndlaapi/controller/UserController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Flag.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Post.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Flag.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Owned.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Post.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Topic.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/database/Compiled.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ConverterService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
myndla/src/main/scala/no/ndla/myndla/repository/UserRepository.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderWriteService.scala
myndla/src/main/scala/no/ndla/myndla/service/UserService.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderReadServiceTest.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderWriteServiceTest.scala
myndla/src/test/scala/no/ndla/myndla/service/UserServiceTest.scala
typescript/myndla-api.ts

Vil også kreve litt oppdateringer i graphql-api og ndla-frontend

Make deleting user not delete topics and posts

---

myndla/src/main/scala/no/ndla/myndla/MyNDLAAuthHelpers.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderConverterService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderWriteService.scala
myndla/src/main/scala/no/ndla/myndla/service/UserService.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderConverterServiceTest.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderWriteServiceTest.scala
myndla/src/test/scala/no/ndla/myndla/service/UserServiceTest.scala

For å slippe å sette flagget manuelt i etterkant kan vi heller sette flagget dersom epost til brukeren ligger i lista. Slik kan vi slette lista etter kvart.

Sets arenaEnabled on user at login

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

relates to https://github.com/NDLANO/editorial-frontend/pull/2218

Add data-concept-type to validation

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

Revert "Add data-concept-type to validation"

---

article-api/src/main/scala/no/ndla/articleapi/service/ConverterService.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleIntroduction.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleTitle.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
draft-api/src/main/scala/no/ndla/draftapi/service/search/SearchConverterService.scala
draft-api/src/test/scala/no/ndla/draftapi/TestData.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala

Usikker på om vi egentlig trenger denne, men tenker @Jonas-C kan meine noko om det er kjekt å ha.
Funksjonaliteten er invertert i forhold til article-api Article.

Add html title-variant in draft-api for ed.

---

myndla-api/src/main/scala/no/ndla/myndlaapi/MyNdlaApiProperties.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/nodebb/NodeBBClient.scala

Gjør det litt enklere å importere data fra nodebb.

Trenger kun env-variabel ved kjøring lokalt.

---

myndla-api/src/main/scala/no/ndla/myndlaapi/service/ImportService.scala

Reserver user

---

concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
concept-api/src/main/scala/no/ndla/conceptapi/db/migration/V9__LanguageUnknownToUnd.scala
concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptContent.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
concept-api/src/main/scala/no/ndla/conceptapi/validation/ContentValidator.scala
concept-api/src/test/scala/no/ndla/conceptapi/TestData.scala
concept-api/src/test/scala/no/ndla/conceptapi/TestEnvironment.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
concept-api/src/test/scala/no/ndla/conceptapi/validation/ContentValidatorTest.scala

~Avventer tilbakemelding fra ndla.~ NDLA seier kjør!
Legger til støtte for å lagre html i forklaring på samme måte som for artikkelingress.

Html concept content

---

concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala

Pass på at søkbare felt er uten html-tags

Parse new html-fields to searchable values

---

.github/workflows/typescript-generate.yml
search-api/src/main/scala/no/ndla/searchapi/model/api/MultiSearchSummary.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
typescript/types-backend/search-api.ts

Viser seg at noen har lyst til å hente ut feltet også ikke bare filtrere på det :smile:

search-api: Add published field to search result

---

myndla-api/README.md

Fixes https://github.com/NDLANO/Issues/issues/3866
Vet ikke helt hva vi vil ha i disse lenger jeg 😄

myndla-api: readme

---

draft-api/src/main/scala/no/ndla/draftapi/service/StateTransitionRules.scala
draft-api/src/test/scala/no/ndla/draftapi/service/StateTransitionRulesTest.scala

draft-api: Stop restricting unpublish based on other drafts

---

network/src/main/scala/no/ndla/network/clients/FeideApiClient.scala

Gir lærertilgang så lenge en person har en ansattrolle

Don't be so strict in role checks

---

myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/controller/StatsControllerTest.scala
myndla/src/main/scala/no/ndla/myndla/repository/FolderRepository.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala

Fixes https://github.com/NDLANO/Issues/issues/3968

myndla-api: Add option to pass multiple resourceTypes to favorites endpoint

---

article-api/src/main/scala/no/ndla/articleapi/model/api/Article.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleContent.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleIntroduction.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleMetaImage.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/ArticleTitle.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/RequiredLibrary.scala
article-api/src/main/scala/no/ndla/articleapi/model/api/VisualElement.scala

Jonas fant noe rusk så da trenger vi å være litt eksplisitte :^)
Fixes https://github.com/NDLANO/Issues/issues/3973

article-api: Fix serialization for related content for articles

---

validation/src/main/resources/embed-tag-rules.json

Add html tags to urltext in campaignblock

---

myndla-api/src/test/scala/no/ndla/myndlaapi/repository/ConfigRepositoryTest.scala
myndla/src/main/scala/no/ndla/myndla/model/domain/config/ConfigMeta.scala
myndla/src/main/scala/no/ndla/myndla/repository/ConfigRepository.scala
myndla/src/main/scala/no/ndla/myndla/service/ConfigService.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderWriteService.scala
myndla/src/test/scala/no/ndla/myndla/service/FolderWriteServiceTest.scala

Return `Try` when fetching `ConfigMeta`

---

network/src/main/scala/no/ndla/network/tapir/Routes.scala
tapirtesting/src/main/scala/no/ndla/tapirtesting/TapirControllerTest.scala

Sikkert ikke så veldig nøye, men denne gjør at vi rydder opp når testene er ferdige :smile:

Add cleanup to `TapirControllerTest`

---

myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/controller/StatsControllerTest.scala
myndla/src/main/scala/no/ndla/myndla/model/api/SingleResourceStats.scala
myndla/src/main/scala/no/ndla/myndla/repository/FolderRepository.scala
myndla/src/main/scala/no/ndla/myndla/service/FolderReadService.scala

Denne er breaking mot ed, så trengs en oppdatering der!

Add possibility to get favorites for multiple resources

---

draft-api/src/main/scala/no/ndla/draftapi/integration/TaxonomyApiClient.scala
draft-api/src/test/scala/no/ndla/draftapi/integration/TaxonomyApiClientTest.scala

Enn så lenge stripper vi html fra det som sendes til taksonomi

Do not send html to taxonomy

---

search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala

Gjør det mogeleg å søke på contextid

Add search for context id

---

concept-api/src/main/scala/no/ndla/conceptapi/controller/ConceptControllerHelpers.scala
draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/controller/SubjectPageController.scala
search-api/src/main/scala/no/ndla/searchapi/controller/SearchController.scala

Didn't think we wanted 0, but we do :^)

Set minimum `page-size` validators to 0

---

common/src/main/scala/no/ndla/common/CirceUtil.scala
image-api/src/main/resources/no/ndla/imageapi/db/migration/V19__add_empty_notes.sql

Var visst noen flere lister som ikke var i alle dokumentene for bilder :smile: 
Wrapper også feil fra `circe` i vår egen exception for å få litt bedre feilmeldinger :smile:

Image api indexing bug

---

search-api/src/main/scala/no/ndla/searchapi/model/api/SubjectAggregations.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
typescript/types-backend/search-api.ts

Katrine lurte meg til å lage dette feil første gangen :smile:

search-api: Return published articles rather than total count in subject

---

article-api/src/test/scala/no/ndla/articleapi/service/ReadServiceTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/UserServiceTest.scala
network/src/main/scala/no/ndla/network/clients/FeideApiClient.scala
network/src/test/scala/no/ndla/network/clients/FeideApiClientTest.scala
search-api/src/test/scala/no/ndla/searchapi/controller/SearchControllerTest.scala

PrimaryAffiliation er ikkje satt for alle fylkeskommuner, men dersom det er satt gjør vi en ekstra sjekk på den

Extra check for primary affiliation

---

myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V10__favorited_date.sql
myndla-api/src/main/scala/no/ndla/myndlaapi/controller/FolderController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/domain/FolderResource.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderWriteService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/CloneFolderTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderWriteServiceTest.scala

- Legger til ny kolonne i folder_resources: favorited_date 
- Legger til `/folders/resources/recent` endepunkt som henter ut id'en til siste hjertemarkerte ressurs

myndla-api: get latest favorited resource

---

audio-api/src/main/scala/no/ndla/audioapi/controller/HealthController.scala
audio-api/src/test/scala/no/ndla/audioapi/controller/HealthControllerTest.scala
image-api/src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
image-api/src/main/scala/no/ndla/imageapi/controller/HealthController.scala
image-api/src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala
image-api/src/test/scala/no/ndla/imageapi/TestEnvironment.scala
image-api/src/test/scala/no/ndla/imageapi/controller/HealthControllerTest.scala

Nytt forslag. Sjekker aws om fila finnes heller enn gjøre api-kall.

Replace http-check for aws check

---

image-api/src/main/scala/no/ndla/imageapi/controller/RawController.scala

Er det en grunn til at controller ikkje er i swagger?

viser raw controller i swagger

---

image-api/src/main/scala/no/ndla/imageapi/controller/RawController.scala
image-api/src/main/scala/no/ndla/imageapi/service/ReadService.scala
image-api/src/test/scala/no/ndla/imageapi/controller/RawControllerTest.scala
image-api/src/test/scala/no/ndla/imageapi/service/ReadServiceTest.scala

image-api: Handle encoded image urls

---

image-api/src/main/scala/no/ndla/imageapi/model/api/Error.scala
network/src/main/scala/no/ndla/network/tapir/TapirErrorHelpers.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/controller/OEmbedProxyController.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedServiceComponent.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala
oembed-proxy/src/test/scala/no/ndla/oembedproxy/controller/OEmbedProxyControllerTest.scala

Also pass along more client errors rather than saying 502.

oembed-proxy: Add url validation

---

network/src/main/scala/no/ndla/network/tapir/Routes.scala

Endrer så labelen for prometheus metrikkene blir nøyaktige.
Feks `200` `410` `502` istedetfor `2xx`, `4xx` og `5xx`.
Ser egentlig ingen grunn til å ikke ha dette da vi kan justere queryene til å være `5..` dersom vi kun bryr oss om hvilken type feil noe er.

Update prometheus labels to include explicit status code

---

audio-api/src/main/resources/no/ndla/audioapi/db/migration/V21__tsm_system_rows_extension.sql
audio-api/src/main/scala/no/ndla/audioapi/repository/AudioRepository.scala
image-api/src/main/resources/no/ndla/imageapi/db/migration/V20__tsm_system_rows_extension.sql
image-api/src/main/scala/no/ndla/imageapi/ComponentRegistry.scala
image-api/src/main/scala/no/ndla/imageapi/repository/ImageRepository.scala

Bruker postgres-plugin for kjappere helsesjekk. 
For image-api gikk `explain select` beregninga av kost for spørring fra over 30000 til 0.05. Det er en forbedring.

Better health check

---

common/src/main/scala/no/ndla/common/model/domain/draft/QualityEvaluation.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/QualityEvaluation.scala
typescript/types-backend/draft-api.ts

Kom inn ønske om at note skal være optional!

Note in QualityEvaluation is optional

---

concept-api/src/main/scala/no/ndla/conceptapi/controller/PublishedConceptController.scala

Fikser 404 på https://liste.test.ndla.no/?subjects%5B%5D=urn%3Asubject%3Aa591b92a-5355-4b73-acf2-27a0ebe1f300

Fikser at liste.ndla.no krasjer dersom søket gir tom liste.

---

search/src/main/scala/no/ndla/search/BaseIndexService.scala

Hiver på noe logging for oppdatering av index-replicas :smile:

search: Add logging to replica number updating

---

search-api/src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableTaxonomyContext.scala
search-api/src/main/scala/no/ndla/searchapi/model/taxonomy/Node.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala

Legger til unik url for kontekst til søkeindeks slik at vi kan hente ut dette fra søket også.

Add url from context to search-api index

---

concept-api/src/main/scala/no/ndla/conceptapi/ComponentRegistry.scala
concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
concept-api/src/main/scala/no/ndla/conceptapi/integration/SearchApiClient.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ImportService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ReadService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/StateTransitionRules.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/WriteService.scala
concept-api/src/test/scala/no/ndla/conceptapi/TestEnvironment.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala
search-api/src/main/scala/no/ndla/searchapi/controller/InternController.scala

Trigger indeksering av forklaring i søkeapi ved lagring.

Index concept in search-api on save

---

draft-api/src/main/scala/no/ndla/draftapi/db/migration/V58__MigrateSavedSearchUrls.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V58__MigrateSavedSearchUrlsTest.scala

Superenkel migrering av lagra forklaringssøk

Convert concept-search to content-search

---

myndla-api/src/main/resources/no/ndla/myndlaapi/db/migration/V13__answering_posts_with_post.sql
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/nodebb/NodebbModels.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/NewPost.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/api/Post.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/arena/domain/Post.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ConverterService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ImportService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala
oembed-proxy/src/test/scala/no/ndla/oembedproxy/service/OEmbedConverterServiceTest.scala
typescript/types-backend/myndla-api.ts

Implemented subposts column on posts table. Added logic for adding neste posts

Subposts i Arena

---

myndla-api/src/main/scala/no/ndla/myndlaapi/repository/ArenaRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/e2e/ArenaTest.scala

Ser ut som vi innførte en bug her med upvotes, så laget en test på det og fikset feilen.

Fix bug where fetching flagged posts failed with upvotes

---

image-api/src/main/scala/no/ndla/imageapi/service/ImageStorageService.scala

Gjør litt logg-rydding :smile:

image-api: Be more specific about the error message

---

article-api/src/main/scala/no/ndla/articleapi/Main.scala
audio-api/src/main/scala/no/ndla/audioapi/Main.scala
common/src/main/scala/no/ndla/common/errors/ExceptionLogHandler.scala
concept-api/src/main/scala/no/ndla/conceptapi/Main.scala
draft-api/src/main/scala/no/ndla/draftapi/Main.scala
frontpage-api/src/main/scala/no/ndla/frontpageapi/Main.scala
image-api/src/main/scala/no/ndla/imageapi/Main.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/Main.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/Main.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/Main.scala
search-api/src/main/scala/no/ndla/searchapi/Main.scala

Så at exceptions som når toppen og avslutter applikasjonen ble logget på "standard måte" som plaintext så tenkte det var digg å få de ut som json så de kan bli parset på samme måte som andre exceptions.

Add exception handler for uncaught exceptions

---

search-api/src/main/scala/no/ndla/searchapi/model/api/ApiTaxonomyContext.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala

Returnerer contextid for søkekontekster

Return contextId from index

---

.github/workflows/article-api_release.yml
.github/workflows/audio-api_release.yml
.github/workflows/concept-api_release.yml
.github/workflows/draft-api_release.yml
.github/workflows/frontpage-api_release.yml
.github/workflows/image-api_release.yml
.github/workflows/learningpath-api_release.yml
.github/workflows/myndla-api_release.yml
.github/workflows/oembed-proxy_release.yml
.github/workflows/search-api_release.yml

Revert keyring change

---

article-api/src/main/scala/no/ndla/articleapi/db/migration/V49__RemoveConceptListEmbeds.scala
article-api/src/test/scala/no/ndla/articleapi/db/migration/V49__RemoveConceptListEmbedsTest.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migration/V61__RemoveConceptListEmbeds.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V61__RemoveConceptListEmbedsTest.scala
validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

Remove `concept-list` embeds

---

article-api/src/main/scala/no/ndla/articleapi/db/migration/V50__RemoveUnsupportedContactBlockAttributes.scala
article-api/src/test/scala/no/ndla/articleapi/db/migration/V50__RemoveUnsupportedContactBlockAttributesTest.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migration/V62__RemoveUnsupportedContactBlockAttributes.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V62__RemoveUnsupportedContactBlockAttributesTest.scala
validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/TagRules.scala

Contactblock har background nå ikke blob!

Added background as embed-attribute for contact-block

---

article-api/src/main/scala/no/ndla/articleapi/db/HtmlMigration.scala
article-api/src/main/scala/no/ndla/articleapi/db/migration/V51__BodyBoxToFramedContent.scala
article-api/src/test/scala/no/ndla/articleapi/db/migration/V51__BodyBoxToFramedContentTest.scala
draft-api/src/main/scala/no/ndla/draftapi/db/HtmlMigration.scala

@Jonas-C 
Dette burde sikkert vært 2 pr'er, men den migreringsbaseklassen gjorde at det ble fryktelig lett å lage det i en så synd for dere!! :boom:

Convert c-bodybox to framed-content

---

article-api/src/main/scala/no/ndla/articleapi/db/migration/V52__ConvertBlogPostToPitch.scala
article-api/src/test/scala/no/ndla/articleapi/db/migration/V52__ConvertBlogPostToPitchTest.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migration/V63__ConvertBlogPostToPitch.scala
draft-api/src/test/scala/no/ndla/draftapi/db/migration/V63__ConvertBlogPostToPitchTest.scala
validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

Ut med blogpost og inn med pitch

Converts blogposts to pitch

---

article-api/src/main/scala/no/ndla/articleapi/model/api/PartialPublishArticle.scala
article-api/src/main/scala/no/ndla/articleapi/service/ConverterService.scala
article-api/src/test/scala/no/ndla/articleapi/service/ConverterServiceTest.scala
draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/PartialPublishArticle.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala

https://trello.com/c/Pc4rwZlN/1071-endring-av-datoen-sist-faglig-oppdater-skal-ikke-generere-endring-statusendring-av-artikkel
Delpublisering av publisert-dato

Add support for partial publishing publised date

---

search-api/src/main/scala/no/ndla/searchapi/model/api/Title.scala
search-api/src/main/scala/no/ndla/searchapi/model/api/article/ArticleIntroduction.scala
search-api/src/main/scala/no/ndla/searchapi/model/domain/ArticleApiSearchResult.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
search-api/src/main/scala/no/ndla/searchapi/service/ConverterService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/ArticleIndexServiceTest.scala

Legger til domainobject i indeks og bruker dette for å returnerer tittel og intro med htmlvarianter.

Add html variants to title and introduction

---

project/searchapi.scala
typescript/types-backend/search-api.ts

search-api: Generate typescript type for `SearchParams`

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ReadService.scala

Learningpath-frontend funker likevel. Forskjellene mellom LearningPathV2 og LearningPathSummaryV2 ignorerers ved framvisning av egne stier.

Return full learningpath when fetching mine

---

common/src/main/scala/no/ndla/common/model/domain/learningpath/LearningPath.scala
learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V41__RemoveUnintendedLearningstepsField.sql

Fikser broken læringssteg :grimacing:

learningpath-api: Fix learningstep fetching

---

database/src/main/scala/no/ndla/database/TableMigration.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/ComponentRegistry.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/db/migrationwithdependencies/V16__MigrateResourcePaths.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/SearchApiClient.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/TaxonomyApiClient.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala

~Må vente til vi har skrudd på korte urler i prod~
No kan denne tas inn

Add migration to convert resource paths

---

common/src/main/scala/no/ndla/common/model/domain/learningpath/EmbedUrl.scala

Dette var enklere enn forventet :thinking:

learningpath-api: Add `external` embed url to learningsteps

---

search-api/src/main/scala/no/ndla/searchapi/integration/GrepApiClient.scala
search-api/src/main/scala/no/ndla/searchapi/model/api/grep/GrepResultDTO.scala
search-api/src/main/scala/no/ndla/searchapi/model/grep/GrepBundle.scala
search-api/src/main/scala/no/ndla/searchapi/model/grep/GrepElement.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableGrepElement.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/GrepIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/GrepSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/GrepSearchServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/SearchConverterServiceTest.scala

Relates to https://github.com/NDLANO/Issues/issues/4244

search-api: Add grep læreplan to indexed search

---

common/src/main/scala/no/ndla/common/model/domain/learningpath/LearningPath.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/StatsController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/SwaggerDocControllerConfig.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/OembedProxyClient.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/SearchApiClient.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/integration/TaxonomyApiClient.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/domain/Sort.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/DurationValidator.scala

Fixes https://github.com/NDLANO/Issues/issues/4252
Utvider isPrivate med Ready for sharing.

Fix isprivate

---

article-api/src/main/scala/no/ndla/articleapi/ComponentRegistry.scala
article-api/src/main/scala/no/ndla/articleapi/db/migrationwithdependencies/V55__SetHideBylineForImagesNotCopyrighted.scala
article-api/src/main/scala/no/ndla/articleapi/integration/ImageApiClient.scala
article-api/src/test/scala/no/ndla/articleapi/TestEnvironment.scala
draft-api/src/main/scala/no/ndla/draftapi/ComponentRegistry.scala
draft-api/src/main/scala/no/ndla/draftapi/db/migrationwithdependencies/V66__SetHideBylineForImagesNotCopyrighted.scala
draft-api/src/main/scala/no/ndla/draftapi/integration/ImageApiClient.scala
draft-api/src/test/scala/no/ndla/draftapi/TestEnvironment.scala

…ighted
Fixes https://github.com/NDLANO/Issues/issues/4248
Forholdsvis tidkrevende migrering. article-api tok 21 min lokalt.
2 timer på draft.... Kanskje ikkje konvertere avpubliserte artikler.

Sett hidebyline på bilder i artikler som ikkje er copyrighta

---

scalatestsuite/src/main/scala/no/ndla/scalatestsuite/IntegrationSuite.scala

Ryddig at denne matcher miljøene: https://github.com/NDLANO/deploy/pull/1015

Bump postgres version in tests

---

.github/workflows/article-api_ci.yml
.github/workflows/audio-api_ci.yml
.github/workflows/common_ci.yml
.github/workflows/concept-api_ci.yml
.github/workflows/constants_ci.yml
.github/workflows/database_ci.yml
.github/workflows/draft-api_ci.yml
.github/workflows/formatting.yml
.github/workflows/frontpage-api_ci.yml
.github/workflows/image-api_ci.yml
.github/workflows/integration-tests_ci.yml
.github/workflows/language_ci.yml
.github/workflows/learningpath-api_ci.yml
.github/workflows/mapping_ci.yml
.github/workflows/myndla-api_ci.yml
.github/workflows/network_ci.yml
.github/workflows/oembed-proxy_ci.yml
.github/workflows/scalatestsuite_ci.yml
.github/workflows/search-api_ci.yml
.github/workflows/search_ci.yml
.github/workflows/tapirtesting_ci.yml
.github/workflows/typescript-generate.yml
.github/workflows/validation_ci.yml
project/GithubWorkflowPlugin.scala

Add sbt-runner

---

myndla-api/src/main/scala/no/ndla/myndlaapi/db/migration/V17__AddArenaAcceptedField.scala

Whops, glemte denne :nerd_face:

myndla-api: Add `arenaAccepted` field migration

---

myndla-api/src/main/scala/no/ndla/myndlaapi/controller/ArenaController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/controller/UserController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/nodebb/NodeBBClient.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/nodebb/NodebbModels.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/ArenaReadService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderConverterService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/UserService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderConverterServiceTest.scala

Legger til kall til nodebb ved setting av `arenaAccepted=true`.
Og sletter nodebb bruker ved kall til delete all personal data endepunktet.

myndla-api: Add creating & deleting of nodebb user

---

myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderConverterService.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/UserService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderConverterServiceTest.scala

Angelica fikk ikkje lov til å godta arena fordi gammel løsning ikkje tok hensyn til at hennar org var i lista over godkjente orger.

also take orgs into consideration

---

image-api/src/main/scala/no/ndla/imageapi/controller/BaseImageController.scala
image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV3.scala
image-api/src/main/scala/no/ndla/imageapi/model/api/SearchParamsDTO.scala
image-api/src/main/scala/no/ndla/imageapi/model/domain/SearchSettings.scala
image-api/src/main/scala/no/ndla/imageapi/model/search/SearchableImage.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/ImageIndexService.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/ImageSearchService.scala
image-api/src/main/scala/no/ndla/imageapi/service/search/SearchConverterService.scala
image-api/src/test/scala/no/ndla/imageapi/TestData.scala

Relates to https://github.com/ndlano/issues/issues/4277

image-api: Add `users`-filter to image search

---

concept-api/src/main/scala/no/ndla/conceptapi/ComponentRegistry.scala
concept-api/src/main/scala/no/ndla/conceptapi/db/migration/V24__SplitTagsPublished.scala
concept-api/src/main/scala/no/ndla/conceptapi/db/migrationwithdependencies/V25__SubjectNameAsTagsPublished.scala

Glemte visst at det er flere tabeller i concept-api om dagen :nerd_face:

concept-api: Add subject tag migrations for published table

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala

Gjør så vi fallbacker til hva enn brukeren sendte inn istedenfor å konvertere dersom oembed-proxy returnerer 4xx når vi prøver å embedde en ndla adresse.

learningpath-api: Fallback oembed conversion

---

image-api/src/main/scala/no/ndla/imageapi/controller/ImageControllerV3.scala
image-api/src/main/scala/no/ndla/imageapi/controller/multipart/MultipartInput.scala
image-api/src/main/scala/no/ndla/imageapi/service/ValidationService.scala
image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala

Relates to https://github.com/NDLANO/Issues/issues/4290

image-api: Add endpoint for copying image meta with new file

---

common/src/main/scala/no/ndla/common/model/api/learningpath/LearningPathStatsDTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/InternController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponent.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/controller/InternControllerTest.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/ComponentRegistry.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/integration/LearningPathApiClient.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/model/api/StatsDTO.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/UserRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/TestEnvironment.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/controller/StatsControllerTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderReadServiceTest.scala

Fixes NDLANO/Issues#4293
Adds the following statistics:
- numberOfLearningPaths
- users:
- total
- withFavourites
- noFavourites
- arena

Extend user statistics

---

common/src/main/scala/no/ndla/common/model/domain/TryMaybe.scala
common/src/test/scala/no/ndla/common/model/domain/TryMaybeTest.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/controller/StatsController.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/FolderRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/repository/UserRepository.scala
myndla-api/src/main/scala/no/ndla/myndlaapi/service/FolderReadService.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/controller/StatsControllerTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/repository/FolderRepositoryTest.scala
myndla-api/src/test/scala/no/ndla/myndlaapi/service/FolderReadServiceTest.scala

Ref https://github.com/NDLANO/backend/pull/620#discussion_r1988526788
Introduserer en ny klasse `TryMaybe` som i praksis er en  `Try[Option[T]]` med noen hjelpefunksjoner (Og som lar den brukes i for-comprehensions.
Nooen cats-purister ville nok sagt at vi burde brukt en `EitherT`, men jeg syns dette er mer lesbart.
Gjerne utfordre meg der om dere vil :smile:

myndla-api: Update `getStats` error handling to not throw exceptions

---

network/src/main/scala/no/ndla/network/tapir/Routes.scala
project/Dependencies.scala
project/conceptapi.scala
project/imageapi.scala
project/networklib.scala

Bumper alt. Har kjørt gjennom alle tester i apiene og deloya lokalt og alt ser ut til å funke.

All the dependencies

---

.github/workflows/typescript-generate.yml
oembed-proxy/src/main/scala/no/ndla/oembedproxy/OEmbedProxyProperties.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/NDLAErrors.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedDTO.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/model/OEmbedProvider.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedConverterService.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/OEmbedServiceComponent.scala
oembed-proxy/src/main/scala/no/ndla/oembedproxy/service/ProviderService.scala

Kaster ikkje 502 med 400-feil fra ekstern tjeneste.

Pass along 400 from ndla-frontend. Drop listing code

---

image-api/src/main/scala/no/ndla/imageapi/service/WriteService.scala

Add 'copy' to title when copying image

---

search-api/src/main/scala/no/ndla/searchapi/service/search/IndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

En del av dette er veldig prøving og feiling, men her er noen ting vi prøver å oppnå:
- Søk som inkluderer fagnavn skal dukke opp i resultatet / score høyere
- Fag skal dukke opp over artikler om noe matcher
- Søk på nøyaktige titler skal matche bedre / dukke opp høyere
- Fikse fag filtrering så den ikke filtrerer ut fag

Search tweaking

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala

Necessary for NDLANO/Issues#4342

Handle empty string in introduction when creating new learningstep

---

.gitignore
common/src/main/scala/no/ndla/common/configuration/BaseProps.scala
common/src/test/scala/no/ndla/common/configuration/BasePropsTest.scala
project/OpenApiTypescriptPlugin.scala

Denne kunne feile på CI pga concurrency og jeg _tror_ dette løser det :nerd_face: 
Fikset også så loggingen ved loading av props er litt tydeligere

typescript: Fix concurrency problems with `yarn install`

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/TextValidator.scala

Fixes handling of language spans in learningstep descriptions

Add lang and dir to allowed attributes for span in learningstep

---

validation/src/main/resources/embed-tag-rules.json
validation/src/main/scala/no/ndla/validation/EmbedTagRules.scala
validation/src/main/scala/no/ndla/validation/TagRules.scala
validation/src/main/scala/no/ndla/validation/TagValidator.scala
validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala
validation/src/test/scala/no/ndla/validation/EmbedTagValidatorTest.scala

Enkel ndlaembed som kan ha rein tekst som children. Trengs for å kunne vise symbol satt inn i artikkel med egen bakgrunn.
NDLANO/Issues/#4294

Add symbol embed. Make children-prop optional.

---

validation/src/main/scala/no/ndla/validation/TagValidator.scala
validation/src/test/scala/no/ndla/validation/EmbedTagRulesTest.scala

Gjør det litt strengere kva for embeds som har lov til å ha barn

Disallow children if no children rule

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/validation/TextValidator.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/validation/LearningStepValidatorTest.scala

relatert til: https://github.com/NDLANO/Issues/issues/4350

learningpath-api: add h2 and h3 as allowed tags

---

search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala

jeg glemte visst å sjekke alle søkeresultatene vi trengte jeg :nerd_face:

search-api: stop filtering programme contexts when indexing

---

draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/AddMultipleNotesDTO.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/AddNoteDTO.scala
draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala

For å gjøre taksonomi notat oppdateringer enklere

draft-api: add endpoint to bulk add notes to drafts

---

search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableArticle.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableConcept.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableDraft.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableLearningPath.scala
search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableNode.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/ArticleIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/DraftConceptIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/DraftIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/NodeIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableArticleTest.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableDraftTest.scala
search-api/src/test/scala/no/ndla/searchapi/model/search/SearchableLearningPathTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/DraftConceptIndexServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceAtomicTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceTest.scala

Prøver å få boostet opp artikler når man legger til artikkel i søke queryen (og fag mfl.)
Dette viste seg å være litt mer komplekst enn jeg forutså, men dette ser ut til å fungere ganske bra.

search-api: Type keyword search boost

---

search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableSubjectPage.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/MultiSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/NodeIndexService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiSearchServiceAtomicTest.scala
search/src/main/scala/no/ndla/search/model/SearchableLanguageValues.scala

Fikser denne https://trello.com/c/lOA1TmOX/1366-fagforsider-b%C3%B8r-indekseres-til-s%C3%B8ket

search-api: add frontpage metadata to search index

---

article-api/src/main/scala/no/ndla/articleapi/controller/InternController.scala
audio-api/src/main/scala/no/ndla/audioapi/controller/InternController.scala
draft-api/src/main/scala/no/ndla/draftapi/DraftApiProperties.scala
draft-api/src/main/scala/no/ndla/draftapi/controller/InternController.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/InternController.scala

Berre la merke til at det var en del forskjell på logginga etter indeksering. Dette gjør det litt (meir) konsistent.

Harmonize index log messages.

---

search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala

Fikser så søkeoperatorer i bruker id filteret ikke fungerer 🤓

search-api: fix bug with search operators in users filter

---

common/src/main/scala/no/ndla/common/TryUtil.scala
draft-api/src/main/scala/no/ndla/draftapi/DraftUtil.scala
draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
draft-api/src/main/scala/no/ndla/draftapi/integration/ArticleApiClient.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/ArticleRevisionHistoryDTO.scala
draft-api/src/main/scala/no/ndla/draftapi/model/api/NDLAErrors.scala
draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ConverterService.scala
draft-api/src/main/scala/no/ndla/draftapi/service/ReadService.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/DraftUtilTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala

Necessary for NDLANO/Issues#4374

Add enpoint for deleting current revision of a draft

---

search-api/src/main/scala/no/ndla/searchapi/service/search/MultiDraftSearchService.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/MultiDraftSearchServiceTest.scala

Behandler sletta og avpubliserte likt.

Only return unpublished if requested

---

concept-api/src/main/scala/no/ndla/conceptapi/model/api/ConceptTitleDTO.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/ConverterService.scala
concept-api/src/main/scala/no/ndla/conceptapi/service/search/SearchConverterService.scala
concept-api/src/test/scala/no/ndla/conceptapi/TestData.scala
concept-api/src/test/scala/no/ndla/conceptapi/service/WriteServiceTest.scala

Add support for HTML in concept title

---

concept-api/src/main/scala/no/ndla/conceptapi/ConceptApiProperties.scala
concept-api/src/main/scala/no/ndla/conceptapi/validation/ContentValidator.scala

Allow HTML tags when validating concept title

---

common/src/main/scala/no/ndla/common/model/domain/learningpath/LearningPath.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/LearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/LearningpathResponsibleDTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/NewLearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/UpdatedLearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/LearningPathAndStepCreationTests.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponentIntegrationTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/validation/LearningPathValidatorTest.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala

Krysset fingre for at Jonas ikke hadde dette lokalt. Mangler sikkert et eller annet, og må garantert tilpasse det når status lander.

feat: add responsible to learningpath

---

common/src/main/scala/no/ndla/common/model/domain/learningpath/LearningPath.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/ComponentRegistry.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/db/migration/V45__AddComments.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/LearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/NewLearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/model/api/UpdatedLearningPathV2DTO.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestData.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/TestEnvironment.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/e2e/LearningPathAndStepCreationTests.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/repository/LearningPathRepositoryComponentIntegrationTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ConverterServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/ReadServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/search/SearchServiceTest.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/validation/LearningPathValidatorTest.scala
search-api/src/test/scala/no/ndla/searchapi/TestData.scala

Skal vi tillate at man legger til nye kommentarer når man kopierer en læringssti? Skal jeg legge inn støtte for kommentarer i søk her, eller skal vi vente? Trengs det i det hele tatt?

add learningpath comments

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/controller/LearningpathControllerV2.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala
learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala
learningpath-api/src/test/scala/no/ndla/learningpathapi/service/UpdateServiceTest.scala

Add endpoint for deleting language of learning path

---

draft-api/src/main/resources/no/ndla/draftapi/db/migration/V75__AddLatestEditedLearingpaths.sql
draft-api/src/main/scala/no/ndla/draftapi/model/api/UpdatedUserDataDTO.scala
draft-api/src/main/scala/no/ndla/draftapi/model/domain/Content.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/TestData.scala

Add support for last edited learningpaths

---

learningpath-api/src/main/resources/no/ndla/learningpathapi/db/migration/V48__RemoveOldFolderTables.sql

Trengs ikkje i learningpath-api lenger

Drop tables for functions moved to myndla-api

---

search-api/src/main/scala/no/ndla/searchapi/model/search/SearchableGrepElement.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/GrepSearchService.scala
search-api/src/main/scala/no/ndla/searchapi/service/search/SearchConverterService.scala
search-api/src/test/scala/no/ndla/searchapi/service/search/GrepSearchServiceTest.scala

Døper om leareplanCode til belongsTo for å kunne filtrere på begge belongsTo felta for grep element.

Add possibility to filter by kompetansemaalsett

---

draft-api/src/main/scala/no/ndla/draftapi/controller/DraftController.scala
draft-api/src/main/scala/no/ndla/draftapi/repository/DraftRepository.scala
draft-api/src/main/scala/no/ndla/draftapi/service/WriteService.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ConverterServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/ReadServiceTest.scala
draft-api/src/test/scala/no/ndla/draftapi/service/WriteServiceTest.scala

Prøver heller å oppdatere fra tax dersom 409

Turn off updatelock

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/service/UpdateService.scala

Gjør det mulig å slette steg du ikkje eiger.

Allow status change for step

---

learningpath-api/src/main/scala/no/ndla/learningpathapi/service/ConverterService.scala

myNdlaOwner settes ikkje ved kopiering av sti. Dette fikser det.

Make sure copying learningpaths updates isMyNDLAOwner
